### ISSUE TITLE
feature confirmation

### ISSUE THREAD

**Issue by ArkAngels** [vn-ki/anime-downloader#105]
When I tried to download an anime, it says the episode is already downloaded and skipping download but it still download it anyway and overwriting my current dir. Is it a bug or not? if not may I ask to make it skip the already downloaded file completely? 

thank you before.

**Comment by freddiaN** [comment]
can you give the full output of the command with the `-ll DEBUG` flag added to it?

**Comment by MichaelDavidJohnson** [comment]
Closing because inactivity, if you still have this issue open it again.
