### ISSUE TITLE
Internet Download Manager Support

### ISSUE THREAD

**Issue by retardedloozer** [vn-ki/anime-downloader#111]
There is a external download manager support but I don't know if it supports IDM and I don't know how to path to it. I copy and paste the path to the .exe but it just starts making errors. Is aria2c the only external download manager it supports? If it is, is it possible to support others like IDM? IDM downloads way faster and i dont want to have to DL aria2. If this is not possible, I will stick with the default download manager. 

Ty for your time and ty for this awesome script. Its super cool and I appreciate it

**Comment by WhoPunkedU** [comment]
I use IDM to download, but not by using the path. You can use -url and it displays the download URLs of the individual episodes in order. You can then copy and paste them into IDM, and they will be in order. Because they are in order, you can rename them accordingly. It is complicated but not too bad once you get the hang of it.

**Comment by retardedloozer** [comment]
> I use IDM to download, but not by using the path. You can use -url and it displays the download URLs of the individual episodes in order. You can then copy and paste them into IDM, and they will be in order. Because they are in order, you can rename them accordingly. The only problem is that sometimes a few of the URLs don't work and you have to switch providers. It is complicated but not too bad once you get the hang of it.

Yeah fair stuff I figured that out eventually but I think using batch clipboard or something as well as giving the files proper names automatically would really help. It's just a suggestion though, the program without this feature still works better than any batch anime downloader ive ever used

**Comment by vn-ki** [comment]
This can be done.

Ref: https://www.internetdownloadmanager.com/support/command_line.html

I don't use windows but I'll be more than happy to merge a PR if someone opens it.
