### ISSUE TITLE
NoneType' object has no attribute 'find_all

### ISSUE THREAD

**Issue by navidalvee** [vn-ki/anime-downloader#114]
**Describe the bug**

i am finding this, it worked yesterday just fine but today 
as i was trying to download and still trying the downloader is giving this 
message 

https://imgur.com/a/ESyMCXE

<img width="571" alt="screen shot 2018-12-20 at 18 58 10" src="https://user-images.githubusercontent.com/10360652/50278507-84b58f80-048a-11e9-8e87-a97e8a1f2c59.png">

**To reproduce**

```

```

<details>
<summary>LOG</summary>

```



```

**Comment by vn-ki** [comment]
I don't think 9anime works.

**Comment by hazique94** [comment]
9anime is down at that time. Now it works.

**Comment by Azrtheal** [comment]
It's stopped working again. Unable to download from 9anime

**Comment by rjhlt** [comment]
Same issue here
Tried all providers

$anime watch --new 'berserk' --provider PROVIDER_NAME

9anime - 'NoneType' object has no attribute 'find_all'
kissanime - random anime matches instead of the search term
kisscartoon - 'NoneType' object has no attribute 'find_all'
masterani -  Expecting value: line 1 column 1 (char 0)
twist.moe - ModuleNotFoundError: No module named 'Crypto'

**Comment by HAFID-Anas** [comment]
anime-downloader 3.6.3
anime: 'NoneType' object has no attribute 'find_all

**Comment by danherman** [comment]
Same issue here, seemingly regardless of what command I use, search term or provider:

$> anime dl 'code geass'
anime: anime-downloader 3.6.3
anime: 'NoneType' object has no attribute 'find_all'

To get into this state, from a new homebrew install of anime-downloader, I ran:

$> anime dl 'code geass'
[valid output, Ctrl-C to exit]
$> anime dl fullmetal
[valid output, entered a number from list]
Enter the anime no:  [1]: 
anime: Selected Fullmetal Alchemist (Dub)
anime: Extracting episode info from page
Expecting value: line 1 column 1 (char 0)

From that point on, all commands (except "watch --list") give the same error:

$> anime watch --list
anime: anime-downloader 3.6.3
anime: Add something to watch list first.
$> anime dl fullmetal
anime: anime-downloader 3.6.3
anime: 'NoneType' object has no attribute 'find_all'
$> anime dl 'code geass'
anime: anime-downloader 3.6.3
anime: 'NoneType' object has no attribute 'find_all'
$> anime watch --new 'berserk'
anime: anime-downloader 3.6.3
anime: 'NoneType' object has no attribute 'find_all'
