### ISSUE TITLE
Kissanime Not Working

### ISSUE THREAD

**Issue by as280093** [vn-ki/anime-downloader#128]
today i tried the anime dl command with url but it returns

 
![screenshot](https://user-images.githubusercontent.com/25240839/51232937-7d50ab80-198e-11e9-9b17-f929165e0a16.png)

it ends up like this for the first time i have to try 9anime looks like for time being 9anime should work but can anyone see whats the issue

**Comment by IngwiePhoenix** [comment]
```
Ingwie@Ingwies-Macbook-Pro.local /tmp $ anime dl "https://kissanime.cool/watch/akame-ga-kill-dub.7x07/y0zp51"
anime: anime-downloader 3.6.2
anime: Extracting episode info from page
'NoneType' object has no attribute 'find'
Ingwie@Ingwies-Macbook-Pro.local /tmp $ pip3 --version
pip 18.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
Ingwie@Ingwies-Macbook-Pro.local /tmp $ python --version
Python 2.7.10
Ingwie@Ingwies-Macbook-Pro.local /tmp $ python3 --version
Python 3.7.2
```

That doesn't seem right either. Any ideas? I installed `anime-downloader` through `pip3`.

**Comment by vn-ki** [comment]
Is this still happening?

**Comment by as280093** [comment]
> Is this still happening?

yess

**Comment by vn-ki** [comment]
Need more info. Please post logs.

**Comment by kmolivier** [comment]
I have the same issue

**Comment by vn-ki** [comment]
Note to self: Kissanime returns `Not Found`. Investigate why exception is not reaised

**Comment by vn-ki** [comment]
Can you check whether this happens on master? @as280093 @IngwiePhoenix

**Comment by IngwiePhoenix** [comment]
I previously used `pipx` to install this. so how exactly do I run it off Master? I am not a snake guy... ^^;

**Comment by vn-ki** [comment]
This should be fixed in master.

@IngwiePhoenix you can hop on to discord for help with installing the master version.
