### ISSUE TITLE
queue option?

### ISSUE THREAD

**Issue by g4269159** [vn-ki/anime-downloader#130]
It'd be nice if there was an option to queue anime to download one after another
for example
I want to download FMA brotherhood followed by BNHA and the script automatically downloads BNHA after previous task is done

**Comment by rehtlaw** [comment]
`anime dl 'full metal alchemist'; anime dl 'boku no hero academia'`

preferably with URLs though because otherwise you'd need choose the anime it finds.

21 Jan 2019, 06:08 by notifications@github.com:

**Comment by kougamishinyaa** [comment]
I didn't work.....it replies extra command

**Comment by g4269159** [comment]
> I didn't work.....it replies extra argument

please try this

anime dl www.animeurl.com & anime dl www.animeurl2.com

**Comment by kougamishinyaa** [comment]
its leaving download half  a way and skipping to next without completing the previous one??
![screenshot 34](https://user-images.githubusercontent.com/46401062/51784850-0034eb80-2171-11e9-95f5-43f3e0be414b.png)

**Comment by kougamishinyaa** [comment]
Thanks it worked......but why it skipped the download?

**Comment by g4269159** [comment]
hmm u can try a different sever maybe?
also try using a double && sign, it will start the next dowload only if the first completed correctly i think
anime dl www.animeurl.com && anime dl www.animeurl2.com

**Comment by kougamishinyaa** [comment]
Ok thanks

**Comment by miasmaejuices** [comment]
This might be helpful.  I use two files.
A script called "download.sh"
A URL list called "download.txt"

The content of "download.sh" is

```
#!/bin/bash
while IFS= read -r line
do
	anime dl $line -f -q 1080p -fq "['720p','480p','320p']" -xd "{aria2}"
done < "download.txt"
```

In the "download.txt", I add a list of URL's I want to download like this:

```
https://animewebsite/showname1
https://animewebsite/showname2
```
You can even append the episodes you want like this:

```
https://animewebsite/showname1 -e 12
https://animewebsite/showname2 -e 4:10
```

Save the files, and run:

```
$ ./download.sh
```

Perhaps others might find it helpful.
