### ISSUE TITLE
parallel downloads

### ISSUE THREAD

**Issue by Meisterlala** [vn-ki/anime-downloader#139]
Currently each episode is downloaded sequentially. It would be nice if the program would pass all episodes to aria2, so that multiple episodes can be downloaded at the same time.

to do this with aria2 would probably be something like:
"echo "http://ep1.mp4 http://ep2.mp4 http://ep3.mp4" | aria2 -i-"

this loop would need to be skipped:
https://github.com/vn-ki/anime-downloader/blob/7e956a6f0c40e5f0a9b256fde95e10bb77a698d0/anime_downloader/cli.py#L125

**Comment by vn-ki** [comment]
What about links expiring @Meisterlala ?

**Comment by vn-ki** [comment]
Closing due to no response
