### ISSUE TITLE
AnimePahe[Kwik] not working

### ISSUE THREAD

**Issue by 29ayush** [vn-ki/anime-downloader#140]
Kwik changed its format to streaming format, and thus now mp4 isn't available directly
Can be reproduced by trying to download anything from animepahe kwik

**Comment by ngomile** [comment]
Looking at annie or youtube-dl would be a good place to start. Since we would just have to find out how to get the video in DASH format.

**Comment by 29ayush** [comment]
I added a pull request #142 ,
If kwik later removes the option, then I will add the m3u8/DASH download.
