### ISSUE TITLE
Update all anime meta data using watch -U

### ISSUE THREAD

**Issue by ShamsuddohaShameem17** [vn-ki/anime-downloader#148]
**Please add "anime watch -U" command to update all of the meta data for anime.**
Current typing command : "anime watch -u" only updates repo/meta information for newly updated anime.

I have encountered this meta data problem while clearing my pre-fetch and temp folder information. Now anime episodes from my list does not load since they don't have any meta data.

**Comment by vn-ki** [comment]
watch is deprecated.
