### ISSUE TITLE
Kissanime search doesn't work at all

### ISSUE THREAD

**Issue by Arnav71** [vn-ki/anime-downloader#154]
![wtf](https://user-images.githubusercontent.com/16363526/54123694-6080a380-4426-11e9-84a2-b2b44cb90b5e.png)

(See the image)

In this example I tried searching for Naruto,but it returned an anime not related to it.

**Comment by meyerovb** [comment]
did you try it without add the provider param?  just anime dl 'Naruto'

**Comment by vn-ki** [comment]
Is this still hapenning? If yes use the `rewrite` branch and post the output of the log.

**Comment by Arnav71** [comment]
Yup,(sorry but how do I use the rewrite branch??)

**Comment by meyerovb** [comment]
@Arnav71 in github go to the code tab and change the branch dropdown.  you can download that code and run the program from the new folder

**Comment by meyerovb** [comment]
@vn-ki i did this:

pip uninstall anime-downloader

pip install git+https://github.com/vn-ki/anime-downloader.git@rewrite#egg=anime-downloader[cloudflare]

anime dl --provider kisscartoon -xd "{aria2}" hotel

and got this:

ERROR: No module named 'anime_downloader.commands'

Guess I'm not sure how to run the rewrite branch either

**Comment by vn-ki** [comment]
This is probably fixed in master. If not please reopen
