### ISSUE TITLE
Kisscartoon error on hotel transylvania series

### ISSUE THREAD

**Issue by meyerovb** [vn-ki/anime-downloader#157]
anime dl --provider kisscartoon transylvania
Download #1, it pulls the first episode, tries for the second and throws:
KeyError: 'content-length'

**Comment by KiraYamatoSD** [comment]
Kisscartoon has redirected from "kisscartoon.ac" to "kisscartoon.is"

**Comment by vn-ki** [comment]
cfscrape error
