### ISSUE TITLE
Can't perform a search when selecting a provider

### ISSUE THREAD

**Issue by Enderlein** [vn-ki/anime-downloader#16]
When using the new `--provider` option with kissanime, the following error is thrown:

```
(venv) PS D:\git\anime-downloader> anime dl "made in abyss" --provider kissanime
anime: anime-downloader 2.6.0
anime: 'NoneType' object has no attribute 'search'
```

It if I choose 9anime it does allow me to search, but that ends after I make a selection and AnimeDLError is thrown. (seems 9anime changed their token again)

**Comment by vn-ki** [comment]
Did you install cfscrape? I think that's the problem you are facing. cfscrape and nodejs is needed for KissAnime.

**Comment by Enderlein** [comment]
Yep. Installing nodejs fixed the issue.
