### ISSUE TITLE
Quality can't be found

### ISSUE THREAD

**Issue by ArcticJager** [vn-ki/anime-downloader#163]
Describe the bug

Attempting to use watch for any anime results in not finding any video quality to play. Similar experience for the dl command.
To reproduce
Title: That Time I Got Reincarnated as a Slime (Dub)
episodes_done: 19
Length: 21
Provider: 9anime
Type: TV Series
Quality: HD
Available Commands: set, remove, update, watch, download.

Press q to exit [q]: watch
anime: Quality 720p not found. Trying 480p.
anime: Quality 480p not found. Trying 360p.
anime: Playing episode 20
anime:

INFO root: anime-downloader 3.6.2
DEBUG root: Platform: Windows-10-10.0.17134-SP0
DEBUG root: Python 3.7.2
DEBUG root: Anime:
Site: 9anime
Anime: Radiant (Dub)
Episode count: 21
, episodes_done: 2
INFO root: Found Radiant (Dub)
DEBUG root: Sliced epiosdes: [[3, 'opkzwj'], [4, 'pqx54j'], [5, 'nol248'], [6, 'z4ow6l'], [7, 'vo5jj6'], [8, 'l7x926'], [9, 'l7n5z3'], [10, '1x967x'], [11, '0w3x2r'], [12, '40l0po'], [13, 'qj99rn'], [14, 'p7zoq6'], [15, 'n7vz4j'], [16, '3zmxw8'], [17, 'qj4kr5'], [18, 'zv0z3m'], [19, '75mp9j'], [20, 'l0xrnq'], [21, '75x3n6']]
DEBUG root: Extracting stream info of id: opkzwj
DEBUG root: API call URL: https://9anime.to/ajax/episode/info with params {'id': 'opkzwj', 'server': '33', 'ts': 0, '_': 744}
DEBUG root: URL: https://www2.9anime.to/ajax/episode/info?id=opkzwj&server=33&ts=0&_=744
DEBUG root: Returned data: {'grabber': 'https://www2.9anime.to/grabber-api/?server=33', 'params': [], 'backup': 0, 'target': 'https://www.rapidvideo.com/e/FX49TBAIRF', 'type': 'iframe', 'name': '03', 'subtitle': ''}
DEBUG root: Sources :
DEBUG root: Calling Rapid url: https://www.rapidvideo.com/e/FX49TBAIRF&q=720p
WARNING root: Quality 720p not found. Trying 480p.
DEBUG root: API call URL: https://9anime.to/ajax/episode/info with params {'id': 'opkzwj', 'server': '33', 'ts': 0, '_': 744}
DEBUG root: URL: https://www2.9anime.to/ajax/episode/info?id=opkzwj&server=33&ts=0&_=744
DEBUG root: Returned data: {'grabber': 'https://www2.9anime.to/grabber-api/?server=33', 'params': [], 'backup': 0, 'target': 'https://www.rapidvideo.com/e/FX49TBAIRF', 'type': 'iframe', 'name': '03', 'subtitle': ''}
DEBUG root: Sources :
DEBUG root: Calling Rapid url: https://www.rapidvideo.com/e/FX49TBAIRF&q=480p
WARNING root: Quality 480p not found. Trying 360p.
DEBUG root: API call URL: https://9anime.to/ajax/episode/info with params {'id': 'opkzwj', 'server': '33', 'ts': 0, '_': 744}
DEBUG root: URL: https://www2.9anime.to/ajax/episode/info?id=opkzwj&server=33&ts=0&_=744
DEBUG root: Returned data: {'grabber': 'https://www2.9anime.to/grabber-api/?server=33', 'params': [], 'backup': 0, 'target': 'https://www.rapidvideo.com/e/FX49TBAIRF', 'type': 'iframe', 'name': '03', 'subtitle': ''}
DEBUG root: Sources :
DEBUG root: Calling Rapid url: https://www.rapidvideo.com/e/FX49TBAIRF&q=360p
INFO root: Playing episode 3
DEBUG root: Calling Rapid url: https://www.rapidvideo.com/e/FX49TBAIRF&q=360p
ERROR root:

**Comment by vn-ki** [comment]
Fixed in 3.6.3
