### ISSUE TITLE
Disabling ssl certificate verification.

### ISSUE THREAD

**Issue by Arnav71** [vn-ki/anime-downloader#167]
**Describe the bug**

`anime: Retrying (Retry(total=9, connect=10, read=10, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),)': /e/G05Q0SY54U&q=720p
anime: Retrying (Retry(total=8, connect=10, read=10, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),)': /e/G05Q0SY54U&q=720p
anime: Retrying (Retry(total=7, connect=10, read=10, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),)': /e/G05Q0SY54U&q=720p
`

How do I disable ssl-certificate authentication in `anime-downloader`. I am aware of the --disable-ssl command, still there's a problem with this.

In this example I am using 9anime as the provider,I am guessing it's not allowing rapidvideo to be used.

**Comment by vn-ki** [comment]
It is the one and only way.
