### ISSUE TITLE
Changing Directory

### ISSUE THREAD

**Issue by stevensonTheKing** [vn-ki/anime-downloader#168]
So I changed the default directory from the config.json file
but it's just creating another folder in the c/users/user named E as the screenshot shows
any possible explanation on how to change the directory?
![Screenshot (73)](https://user-images.githubusercontent.com/49082523/55268721-1f491a00-5295-11e9-9dc7-b5b0a341d598.png)

**Comment by vn-ki** [comment]
```
E://Anime//
```

I think. I don't use windows, maybe someone else can correct me.
