### ISSUE TITLE
Specify Start without End episode

### ISSUE THREAD

**Issue by UsamaAshraf82** [vn-ki/anime-downloader#173]
**Feature**
Feature to insert anime starting episode without giving end episode of anime

e.g
I want to download from episode 20 to onward all episodes of the Anime.

**Comment by 29ayush** [comment]
Already There:

anime dl `anime name/url` -e **start_episode:** 

Basically start_episode then a colon 

FYI 
To download latest episode
anime dl `anime name/url` -e 0

**Comment by UsamaAshraf82** [comment]
OK Thanks , i not figure that out.
