### ISSUE TITLE
Config: Setting {aria2} within config.json does not make aria the default downloader.

### ISSUE THREAD

**Issue by IngwiePhoenix** [vn-ki/anime-downloader#178]
**Describe the bug**
I have edited the `config.json` in hopes that it will use `aria2c` by default, but it did not.

**To reproduce**
```json
{
    "dl": {
        "download_dir": ".",
        "force_download": false,
        "file_format": "{anime_title}/{anime_title}_{ep_no}",
        "log_level": "INFO",
        "player": null,
        "quality": "1080p",
        "skip_download": false,
        "url": false,
        "external_downloader": "{aria2}"
    },
    "watch": {
        "log_level": "INFO",
        "quality": "1080p"
    }
}
```

This config is used. I referenced the added `external_downloader` key from here: https://github.com/vn-ki/anime-downloader/blob/master/anime_downloader/config.py#L21 and here: https://github.com/vn-ki/anime-downloader/blob/master/anime_downloader/config.py#L79

I still have to use `-xd "{aria2}"` in order to get the `aria2c` downloader... What did I do wrong?

Also:
```
Ingwie@Ingwies-Macbook-Pro.local /V/Anime $ pip3 show anime-downloader
Name: anime-downloader
Version: 3.6.2
Summary: Download your favourite anime
Home-page: https://github.com/vn-ki/anime-downloader
Author: Vishnunarayan K.I.
Author-email: vishnunarayan6105@gmail.com
License: UNKNOWN
Location: /usr/local/lib/python3.7/site-packages
Requires: requests, beautifulsoup4, Click, fuzzywuzzy
Required-by: 
Ingwie@Ingwies-Macbook-Pro.local /V/Anime $ anime --version
anime, version 3.6.2
Ingwie@Ingwies-Macbook-Pro.local /V/Anime $ which anime
/usr/local/bin/anime
Ingwie@Ingwies-Macbook-Pro.local /V/Anime $ cat (which anime)
#!/usr/local/opt/python/bin/python3.7

# -*- coding: utf-8 -*-
import re
import sys

from anime_downloader.cli import cli

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(cli())
```

**Comment by IngwiePhoenix** [comment]
Wow, nevermind. Mac OS is a bit different :) From the Click docs:

> click.get_app_dir(app_name, roaming=True, force_posix=False)
> Returns the config folder for the application. The default behavior is to return whatever is most appropriate for the operating system.
> 
> To give you an idea, for an app called "Foo Bar", something like the following folders could be returned:
> 
> Mac OS X:
> ~/Library/Application Support/Foo Bar
> 
> Mac OS X (POSIX):
> ~/.foo-bar
> 
> Unix:
> ~/.config/foo-bar
> 
> Unix (POSIX):
> ~/.foo-bar
> 
> Win XP (roaming):
> C:\Documents and Settings\<user>\Local Settings\Application Data\Foo Bar
> 
> Win XP (not roaming):
> C:\Documents and Settings\<user>\Application Data\Foo Bar
> 
> Win 7 (roaming):
> C:\Users\<user>\AppData\Roaming\Foo Bar
> 
> Win 7 (not roaming):
> C:\Users\<user>\AppData\Local\Foo Bar
> 
> New in version 2.0.

Via: https://click.palletsprojects.com/en/7.x/api/?highlight=get_app_dir#click.get_app_dir

So... I had to look in `~/Library/Application Support/anime downloader/`. Oops!

Might be good to actually reference this piece of documentation in the Wiki's "Configuration" page, since this is obviously something the user should know =)

**Comment by vn-ki** [comment]
Added in wiki

**Comment by gingerbeardman** [comment]
It would be great to have the macOS path listed directly on the wiki page.

Currently it has linux and Windows, macOS is buried behind a link.
