### ISSUE TITLE
kissanime bug

### ISSUE THREAD

**Issue by popcorn9499** [vn-ki/anime-downloader#179]
**Describe the bug**

I attempt to download naruto from kissanime and it fails misserbly. falls on its face even.

**To reproduce**

```
anime dl -q 720p https://kissanime.ru/Anime/Naruto-Shippuuden-Dub/ -e 459:472
```

<details>
<summary>LOG</summary>

```
https://pastebin.com/0gKSAEUJ


```

Hopefully this bug can be sorted out however i have a feeling its a issue with cfscrape

**Comment by vn-ki** [comment]
Do you have node.js installed? If not please install it. It is mentioned in
the install instructions.

**Comment by popcorn9499** [comment]
I have verified and yes i have nodejs installed

Version 11.14.0

**Comment by Anaas75082** [comment]
[kissanime bug.txt](https://github.com/vn-ki/anime-downloader/files/3139331/kissanime.bug.txt)
i cant download any anime on kissanime

**Comment by Anaas75082** [comment]
i cant download any anime in kissanime but works fine on other websites like animepahe
Plzz help
[kissanime bug.txt](https://github.com/vn-ki/anime-downloader/files/3139341/kissanime.bug.txt)

**Comment by vn-ki** [comment]
This is probably the issue with cfscrape. They are fixing it.

**Comment by popcorn9499** [comment]
cfscrape seems to of fixed the issue with cloudflare. I will close as my issue has been resolved
