### ISSUE TITLE
Kissanime search returns episodes rather than series when query returns a single result. 

### ISSUE THREAD

**Issue by Enderlein** [vn-ki/anime-downloader#18]
On kissanime, if your search returns only one result, it automatically takes you to the episode page. This is handy when you're using the site, but it causes problems with the tool.

i.e. If you use the command `anime dl bakemonogatari --provider kissanime`, you get a list that looks like this:
```
 1: Bakemonogatari Episode 015
 2: Bakemonogatari Episode 014
 3: Bakemonogatari Episode 013
 4: Bakemonogatari Episode 012
 5: Bakemonogatari Episode 011
 6: Bakemonogatari Episode 010
 7: Bakemonogatari Episode 009
 8: Bakemonogatari Episode 008
 9: Bakemonogatari Episode 007
10: Bakemonogatari Episode 006
11: Bakemonogatari Episode 005.5 (Recap)
12: Bakemonogatari Episode 005
13: Bakemonogatari Episode 004
14: Bakemonogatari Episode 003
15: Bakemonogatari Episode 002
16: Bakemonogatari Episode 001
```

And if you choose one of the episodes, you get the error `'NoneType' object has no attribute 'text'`

Perhaps the tool could mimic kissanime and just skip the selection process and head straight to downloading the series if there is only one search result.

If you're working on this, the queries "Made in Abyss" and "Saint Young Men" both do the same thing.

**Comment by vn-ki** [comment]
Nice find! You wanna take a dig at it?

**Comment by Enderlein** [comment]
Already working on it.
