### ISSUE TITLE
Feature request: Use episode numbers as given per origin

### ISSUE THREAD

**Issue by IngwiePhoenix** [vn-ki/anime-downloader#180]
I'd like to request an improvement to `file_format`'s configuration, especially for `{ep_no}`.

Sometimes, a series may not be completely uploaded, and you might see something like this:
![image](https://user-images.githubusercontent.com/2893716/56928871-6581db00-6ad8-11e9-9fbf-40369b10fd48.png)
( Via: https://www2.gogoanime.io/category/detective-conan-dub )

But, when downloading using this tool, the episode numbers are not properly reproduced:
```
$ ls Detective_Conan_Dub_{309,338,340}.mp4
ls: cannot access 'Detective_Conan_Dub_309.mp4': No such file or directory
ls: cannot access 'Detective_Conan_Dub_338.mp4': No such file or directory
ls: cannot access 'Detective_Conan_Dub_340.mp4': No such file or directory
```

Instead, all episodes are downloaded in a range of `001` to `161`.

A second example is censored and uncensored episodes:
![image](https://user-images.githubusercontent.com/2893716/56929076-f953a700-6ad8-11e9-97e3-28fd93c30a2a.png)
( Via: https://www4.9anime.to/watch/high-school-dxd-hero-dub.nx18/q3xk4j )

In this example, I worked around by downloading specificly the episodes I wanted, and rename them by hand. But it would've been nice to have the downloaded files contain the `-uncensored` part, which would make it much easier to find out if I obtained the right files or not.

What I can gather from looking at 9anime's episode listing, is:
```
<li>
  <a
    data-id="7108ab52151979f05e5878999e9fec9807b349faeb4b4b07af382644e8a505ff"
    data-base="1"
    data-comment="01uncen"
    href="/watch/high-school-dxd-hero-dub.nx18/0v2qo9"
  >
    01-Uncen
  </a>
</li>
```
(I edited the code by hand to make it fit into a comment's width.)

Each `li > a` has `a[data-comment]` as well as an inner text set. So I guess that if you are examining each of these elements for either having `data-comment`, `data-base` or an `.innerHTML` attached, you could possibly offer `{ep_name}` to allow the user to obtain episodes with the contents of the actual link attached to the episode name to be downloaded.

In my case, I am currently renaming all my files to a new structure of `$name S$seasonE$episode`, and it would be helpful if episodes that were missing from the download didn't magically be available, whilst a whole bulk of others would be missing in the end. :)

You think this is doable?

Thanks and kind regards,
Ingwie.

**Comment by vn-ki** [comment]
@pjzzz You want to look into this?

**Comment by pjzzz** [comment]
Cool will look into this

**Comment by MichaelDavidJohnson** [comment]
This one is actually very interesting, this is being closed but added to a new list. I think if this hasn't been fixed yet it's actually a pretty important fix, this may help when we do filtering too
