### ISSUE TITLE
How to update to newest version?

### ISSUE THREAD

**Issue by bengbengsmrade** [vn-ki/anime-downloader#184]
I have version 3.6.2 installed on Windows but I really have no idea how to update to newest version 3.6.3 or even uninstall the current one.
I checked wiki and installation guide but it doesnt mention anything.

pip install anime-downloader[cloudflare] says - Requirement already satisfied for all of those lines.
I tried pip update if it maybe exists but it doesnt. :D

Could you add somewhere on wiki few lines about update & unistall? 

Thank you for this amazing tool and for replying in advance. :D

**Comment by 29ayush** [comment]
> pip install anime-downloader[cloudflare] -U
