### ISSUE TITLE
9anime download does this to my command prompt, help

### ISSUE THREAD

**Issue by RowanSkie** [vn-ki/anime-downloader#185]
When I try to watch or install any anime with 9anime provider, this happens

> anime dl --provider 9anime 'inazuma-eleven'
> [32manime[0m: anime-downloader 3.6.3
> [32manime[0m: [31m'NoneType' object has no attribute 'find_all'[0m

Help?

**Comment by IngwiePhoenix** [comment]
Those are escape codes. They turn into color instructuions on a Linux terminal - but display as complete garbage on Windows. Dont mind them - you may use an alternative terminal if they bug you though...

Now, this is not related to this program, though. :)
