### ISSUE TITLE
mp4upload extractor code not working

### ISSUE THREAD

**Issue by ItachiSharingan** [vn-ki/anime-downloader#189]
**Describe the bug**
mp4upload changed html source, so the regular expression match is flawed

**Comment by Not-James-Bond** [comment]
Can Confirm this. Happening to me too.

**Comment by ngomile** [comment]
Please provide some screenshots of the problem and how to reproduce it.

**Comment by vn-ki** [comment]
@ItachiSharingan Please provide what @ngomile asked for. If no response is heard, I'll close this

**Comment by vn-ki** [comment]
Closing due to no response

**Comment by DaBoss5** [comment]
![Screenshot_20190719-192616](https://user-images.githubusercontent.com/25087116/61557396-0b9c0c00-aa5c-11e9-89f0-edd8b2d94d62.jpg)

@vn-ki, this is what I get.

Also, managed to do it in one of my other scripts without regex. 

I'm assuming that mp4u_embed is the embed html as text and not soup (didn't see it being set to a beautifulsoup object)

So far, all the links I've tried this with have worked:

```
mp4u_embed = BeautifulSoup(mp4u_embed, 'html.paser')

#Named the variable this way since all the info is in the script tag
script = mp4u_embed. find_all(' script')[-1]. text.split('|')
domain = script[-92]
protocol = script[-10]
video_id = script[-11]
stream_url = f'https://{domain}.mp4upload.com:{protocol}/d/{video_id}/video.mp4'
