### ISSUE TITLE
URL filename problem

### ISSUE THREAD

**Issue by WhoPunkedU** [vn-ki/anime-downloader#19]
when I use the `--url` command, then download using IDM, the video files are just a bunch of gibberish that i can't sort out. does anybody have a way to sort them so i can write the correct names for each file? I know this isn't an issue with the software but I don't know what to do with these files.

**Comment by WhoPunkedU** [comment]
never-mind, I found a halfway decent way to sort them. It's a hassle but that's what happens when you want to download an entire series at once.

**Comment by vn-ki** [comment]
I don't use IDM, so I can't comment on it. The best I can say is that I'll look into it if I find some time on a Windows machine. Maybe @Enderlein can comment on it better.

Do you know of some way to inject filenames into downloads for IDM?

**Comment by Enderlein** [comment]
Don't use IDM, so I can't comment either.

**Comment by WhoPunkedU** [comment]
I found a way.

At the end of each link is the filename, so you can order them correctly.

or

If you batch add them to IDM they are already in order, which I found out by doing the first suggestion.

After that you can just rename them and they will be downloaded with that name
