### ISSUE TITLE
weird download issue

### ISSUE THREAD

**Issue by popcorn9499** [vn-ki/anime-downloader#191]
**Describe the bug**

Just trying to download episodes from kissanime of hunter x hunter.

**To reproduce**

```
anime dl -f -q 720p -u https://kissanime.ru/Anime/Hunter-x-Hunter-2011-Dub --download-dir ./ -e 77:142 --log-level DEBUG
```

<details>
<summary>LOG</summary>
https://pastebin.com/EPVXu6wS
</details>

It never used to just give download urls before now it is so I was wondering if I am doing something wrong or if this is a bug.

**Comment by vn-ki** [comment]
-u is urls only without downloading

**Comment by popcorn9499** [comment]
sorry for the ID10T issue. anyways this looks more like a real issue https://pastebin.com/N8qkQsKY 

Command
```
anime dl -f -q 720p https://kissanime.ru/Anime/Hunter-x-Hunter-2011-Dub -e 77:142 --log-level DEBUG
```

Log 
https://pastebin.com/N8qkQsKY

I will try `--disable-ssl` since this looks like a ssl related issue

**Comment by vn-ki** [comment]
Rapidvideo is probably dead

**Comment by vn-ki** [comment]
Cannot reproduce now. Try master.
