### ISSUE TITLE
Homebrew package manager

### ISSUE THREAD

**Issue by mikolaj92** [vn-ki/anime-downloader#192]
Could you add the awesome project to homebrew?
https://docs.brew.sh/Formula-Cookbook

**Comment by vn-ki** [comment]
I won't be doing it as I don't use brew. If someone wants to do it, I can do the necessary help.

**Comment by nandahkrishna** [comment]
I'd like to work on this if possible.

**Comment by vn-ki** [comment]
Sure, go ahead @nandahkrishna

**Comment by nandahkrishna** [comment]
To do this, we require a tarball of the project to be placed in the repo itself. This tarball should be versioned. I think I'll create a PR to do this.

**Comment by nandahkrishna** [comment]
I've created a PR on Homebrew for this. Hopefully it works out well! Thanks.
Link:
https://github.com/Homebrew/homebrew-core/pull/40791

**Comment by nandahkrishna** [comment]
The PR on Homebrew Core is ready to merge, anime-downloader v3.6.3 will soon be available on Homebrew. I guess this issue can be closed @vn-ki.
