### ISSUE TITLE
"data-ts"

### ISSUE THREAD

**Issue by roy959** [vn-ki/anime-downloader#195]
"anime dl "https://www1.9anime.nl/watch/ace-of-diamond-second-season.8xo/njwp0n" -e 38:51 -q 720p"

I enter the above command and this pops up
"[32manime[0m: anime-downloader 3.6.1
[32manime[0m: Extracting episode info from page
'data-ts'"

I dont understand what I am doing wrong. I have entered same commands before to download animes. But today i keep getting this "data-ts". I dont understand why?

Please help me out. Also im not a techie so dont mind the layman language i have used here

**Comment by em0tionull** [comment]
It's the website you're trying to get the anime from I believe. Gogoanime works great for me,.

**Comment by kougamishinyaa** [comment]
Which version r u using?

**Comment by roy959** [comment]
@em0tionull Yeah you are right. Lately I have been using Kissanime.ru and its working fine for me. The problem is with 9anime site. issue #183 explains it might be because of the captcha they recently introduced.
I dont really have a problem anymore so i think i am gonna close this issue

**Comment by kougamishinyaa** [comment]
Which version are u using?
Rewrite or master?

**Comment by roy959** [comment]
@kougamishinyaa I think master.

**Comment by kougamishinyaa** [comment]
I am also using master but only animepahe is working for me,the rest r all dead

**Comment by roy959** [comment]
Try kissanime.ru
The normal kissanime isn't working. Kissanime.ru is cloudflare supported which should work. 
You can also try downloading through torrents from Horrible subs or nayee.is
PS animepahe isn't working for me
