### ISSUE TITLE
360p/480p videos being downloaded instead of 720p

### ISSUE THREAD

**Issue by muvluvalt** [vn-ki/anime-downloader#201]
When I try to download 720p videos, only 360p/480p ones are downloaded. This is despite the fact that 720p videos are actually available on the source site.

![image](https://user-images.githubusercontent.com/40586164/59774921-db3d4280-92e2-11e9-9ea5-51086d06407e.png)
![image](https://user-images.githubusercontent.com/40586164/59775158-48e96e80-92e3-11e9-80f6-7b6977d19955.png)

To reproduce :
`anime dl -xd {aria2} -q 720p -f -e 1 --log-level DEBUG https://www4.gogoanime.io/category/jormungand`

This [480p link](https://www543.playercdn.net/p-dl/3/JvIdmlNMaGaL7lIowKrtlg/1560976436/190128/483FZMHE7EHU8X4KVDTSD.mp4?name=anime_22520.mp4-480.mp4) (starting with www543) is retrieved instead of this [720p](https://www504.playercdn.net/p-dl/2/a_HBye-tT9B9c08dNg2b8g/1560976436/190113/966FZ5P6H1P1XCQ4U1DXO.mp4?name=anime_22520.mp4.mp4) link (starring with www504).

**Comment by Jtgroos** [comment]
Same here, it downloads the 100ish mb versions. i tested this with in linux en windows and with and without Aria2

but never got the 720p or the 1080p versions altho set with in the config.json

hoop this helps to put this problem in the spotligts cause its been open for 26days already

**Comment by MichaelDavidJohnson** [comment]
Video chooses 720p for me, closing.
