### ISSUE TITLE
Command not Found

### ISSUE THREAD

**Issue by ZakaRehman** [vn-ki/anime-downloader#203]
I installed anime-downloader in ubuntu and then when in terminal when I try running the command "anime" it says it is not found

```



```

**Comment by vn-ki** [comment]
I need more info. How did you install it? You OS, etc

**Comment by SwapnilSoni1999** [comment]
actually its not working on windows I have tried with ubuntu subsystem and it works there only i tried to install with pip

**Comment by vn-ki** [comment]
You probably have to add it to your PATH

**Comment by vn-ki** [comment]
Closing due to no response
