### ISSUE TITLE
add 123anime.cc as an alternative for 9anime

### ISSUE THREAD

**Issue by Eren4363** [vn-ki/anime-downloader#206]
**Describe the feature here**
I found an anime website called "123anime.cc". From what I can see, this website looks very much like 9anime but without the captchas that are mentioned in #183

**Comment by kougamishinyaa** [comment]
Seems interesting ಠ ͜ʖ ಠ

**Comment by MichaelDavidJohnson** [comment]
Closing and passed to the active site request on Discord
