### ISSUE TITLE
9anime introduced captcha. You can use `anime -ll DEBUG` to use it.

### ISSUE THREAD

**Issue by retardedloozer** [vn-ki/anime-downloader#211]
When trying to download from 9anime, I get the error in the title. The problem is anime -ll is already set to DEBUG, at least according to my config.json. And when I try to do the command 'anime -ll DEBUG' I get error 

Usage: anime [OPTIONS] COMMAND [ARGS]...
Try "anime --help" for help.

Error: Missing command.

**Comment by vn-ki** [comment]
9anime does not work due to captcha problem. If you really want to use it you have to add `-ll DEBUG`.

```
anime -ll DEBUG dl 'naruto' --provider 9anime
```
