### ISSUE TITLE
trackma integration [bash script example]

### ISSUE THREAD

**Issue by RaitaroH** [vn-ki/anime-downloader#216]
EDIT: I made a repo for this: https://github.com/RaitaroH/adl
The script below will end up out of sync with the above. Feel free to PR :+1: 

Yesterday I was finally fed up with having to search in my history for the command used to watch show X, then hit backspace to edit the number of the episode I want to watch. For that reason I wanted to write a script to fix this... I made it work with some file, but then I remembered ~[trackma](https://github.com/z411/trackma).

This is just a script I will be using from now on. I do not like the "anime watch" thing because it requires a lot of user input, this is lazy af.

I will not say this is an "issue", nor a "request" is more of a... sharing an idea to others that might want to have it. Perhaps a companion script of sorts, something extra.

Requirements:
+ trackma
+ fzf

Features:
+ watch next episode of any show you have currently watching (I have it setup with anilist)
+ allow for updating the anime entry using trackma
+ it could also be expanded to do anything else using trackma's own functions

So here it is:
```bash
  adl() {
    trackma list | awk -F'  ' 'NR>1 {split($4,t,".");gsub(" ", "", $5);split($5,n,"/");print t[1]"|"n[1]"|"n[2]}' |\
      head -n -2 | sed 's/\x1b\[[0-9;]*m//g' > ~/Documents/anime.log
    # awk explination ...
    # delimeter set to 2x space
    # NR>1 ignore first line
    # $4 is the title plus dots ... split allows to remove the dots, sets new result to var t
    # $5 is Current / All episodes split allows to get the current episode number
    # gsub thingy is to remove beggining space " 2" from one digit numbers
    # finally print t[1] = title and n[1] current episode number: result is like so:    Animu|x
    # head is used here to remove the last 2 lines which are also not needed
    # that sed at the end is to strip color from the output
    # finally for real now, output that stuff to a file

    # Retrieve title and nr. cat file only once
    entry="$(cat ~/Documents/anime.log | fzf --height=10% --tac)"
    title="$(echo $entry | cut -d'|' -f1)"
    nr="$(($(echo $entry | cut -d'|' -f2) + 1))" #dat spacing tho
     last="$(echo $entry | cut -d'|' -f3)"

    echo "Next episode, starting from next to last aired, or all available? [N/s/a]"
    read ans
    case $ans in
      ""|"n"|"N")
        echo "Now watching $title, episode #$nr"
        anime dl --play vlc $title --episodes $nr 2> /dev/null ;;
      "s"|"S")
        echo "Now watching $title, starting with episode #$nr"
        anime dl --play vlc $title --episodes $nr:$last 2> /dev/null ;;
      "a"|"A")
        echo "Now watching $title, from the start"
        anime dl --play vlc $title 2> /dev/null ;;
    esac

    echo "Increase nr in anime list? Yes, no, or custom number [Y/n/c]"
    read ans
    case $ans in
      ""|"y"|"Y")
        trackma update $title $nr
        trackma send
        echo "The progress for $title changed to $nr." ;;
      "n"|"N")
        echo "Exiting." ;;
      "c"|"C")
        echo "Enter custom number:"
        read custom
        trackma update $title $custom
        trackma send ;;
    esac
  }
```

**Comment by RaitaroH** [comment]
Required inputs, 3 enters pretty much.
```
$ adl <ENTER>
Next episode, or all available? [n/a]
<ENTER>
Enter the anime no:  [1]:
<ENTER>
> Increase nr in history? [Y/n]
<ENTER>
```
![image](https://user-images.githubusercontent.com/19552720/61543762-c58b7c00-aa4c-11e9-8f59-0c0aa7bc9a23.png)

**Comment by vn-ki** [comment]
Nice. This is great @RaitaroH. Trackma is python too, so there is a possibility we could somehow integrate it into this tool as well.

Thanks for sharing anyway.

**Comment by RaitaroH** [comment]
@vn-ki I modified this quite a bit now, using case 'cus it got more complicated. 
Should I just make a gist or a repo and link it here instead? 
On another hand, I sorta think the script is done for my use but perhaps others might want to modify it and add extra functions.

**Comment by vn-ki** [comment]
Closing because this isn't really an issue
