### ISSUE TITLE
AUR

### ISSUE THREAD

**Issue by Baitinq** [vn-ki/anime-downloader#217]
It would be very nice if this project was available for download at the AUR (Arch User Repository).

Thanks a lot.

**Comment by vn-ki** [comment]
I don't install python apps using AUR. If someone wants to package it, I'm fine. I can accept any PR regarding it.

**Comment by Baitinq** [comment]
I have packaged it to the AUR (https://aur.archlinux.org/packages/anime-downloader-git). Let me know if I missed anything in the PKGBUILD as I am not much of an expert. I tried to make it so that it would install the git version but I am getting an error as soon as I type the 'anime' command 

 `ERROR:  module 'anime_downloader.commands.__init__' has no attribute 'command'`

**Comment by vn-ki** [comment]
Thanks for adding this to the AUR.

The error has been fixed now. Please update.

**Comment by vn-ki** [comment]
@Baitinq It depends on node too
