### ISSUE TITLE
Watch next

### ISSUE THREAD

**Issue by Baitinq** [vn-ki/anime-downloader#219]
It would be nice to have a watch next episode dialog appear when you exit out of the mpv session in the "anime watch" command. That way you wouldnt have to retype everything and would make the experience much more enjoyable.

**Comment by RaitaroH** [comment]
@Baitinq Check out my script for something like that:
https://github.com/RaitaroH/adl

#shamelessplug

**Comment by Baitinq** [comment]
nice, ill check it out

**Comment by Baitinq** [comment]
@RaitaroH It would be great if instead of using VLC adl used mpv (or maybe a setting to configure which video player to use). Otherwise, your wrapper is great and ill probs start using it

**Comment by RaitaroH** [comment]
@Baitinq I will look into it. Might implement it this week, no promises. Never used mpv.

**Comment by vn-ki** [comment]
This will be nice enhancement even though adl exists.

**Comment by MichaelDavidJohnson** [comment]
Fixed this in the recent PR, when you finish a watch you return to the selection of watch, set ect..
