### ISSUE TITLE
Error inside of watch propmpt

### ISSUE THREAD

**Issue by Baitinq** [vn-ki/anime-downloader#220]
When you are inside the watch prompt in which the script asks you to either {watch, set, remove, update, download} and you pick the download option an error pops out saying `ERROR: __init__() got an unexpected keyword argument 'range_size'`.

**Comment by KALRONG** [comment]
Im seeing the same, did you check the solution at https://github.com/vn-ki/anime-downloader/issues/212#issuecomment-511667431?
