### ISSUE TITLE
Update the GIF in readme

### ISSUE THREAD

**Issue by vn-ki** [vn-ki/anime-downloader#229]
Update the gif as it's outdated.

**Comment by dkapur17** [comment]
I would like to take up this issue. TIA

**Comment by TheGamer007** [comment]
Hi! I'd like to take this up.

**Comment by vn-ki** [comment]
Please go ahead

**Comment by TheGamer007** [comment]
Great! I will send a PR on 1st October once progress for Hacktoberfest starts getting tracked.

**Comment by TheGamer007** [comment]
Also note that you need to update the wiki (descriptions and gifs) since they don't completely match the latest version.

**Comment by Harsh-2909** [comment]
Is the issue still open?

**Comment by MichaelDavidJohnson** [comment]
GIF seems fine now.
