### ISSUE TITLE
ERROR: __init__() got an unexpected keyword argument 'range_size'

### ISSUE THREAD

**Issue by mskomek** [vn-ki/anime-downloader#234]
i installed according to wiki but getting this result always
but dont get from 3.6.3 version
 anime: anime-downloader 4.0.0.r1
+--------+-------------------------------------+--------+
|      3 | Baka to Test to Shoukanjuu: Matsuri |        |
|      2 | Baka to Test to Shoukanjuu Ni!      |        |
|      1 | Baka to Test to Shoukanjuu          |        |
|--------+-------------------------------------+--------|
|   SlNo | Title                               | Meta   |
+--------+-------------------------------------+--------+
Enter the anime no:  [1]: 2
anime: Selected Baka to Test to Shoukanjuu Ni!
anime: Extracting episode info from page
anime: Downloading Baka to Test to Shoukanjuu Ni!-1
ERROR: __init__() got an unexpected keyword argument 'range_size'

**Comment by Rudra2002** [comment]
I have the same problem and I am using aria2c 1.35.0 and the anime downloader is 4.0.1.
This is the latest version.What should I do.

**Comment by levaculik2** [comment]
I am having the same problem and I am using aria2c version 1.35.0 and anime downloader is 4.0.1 how do I solve this?

**Comment by Georgantas** [comment]
I debugged it: you need to pass "--external-downloader {aria2}" as an argument to get rid of that error. Even with that though, this shit project will give other problems.

**Comment by Georgantas** [comment]
I debugged it: you need to pass "--external-downloader {aria2}" as an argument to get rid of that error.

**Comment by vn-ki** [comment]
This has been fixed.
