### ISSUE TITLE
Improve quality handling

### ISSUE THREAD

**Issue by vn-ki** [vn-ki/anime-downloader#236]
**Describe the feature here**

Right now it's a grey area. This has to be improved. There are many issues referencing this issue.

I would like to hear the opinions of @ngomile on this.

Refs: #115

**Comment by ngomile** [comment]
@vn-ki I suggest separating the responsibility of handling qualities be solely left to the AnimeEpisode class, AnimeEpisode subclasses should be allowed to decide whether or not the quality specified is available or not. Because right now its too rigid in my view.

**Comment by MichaelDavidJohnson** [comment]
Closing just to add to the issue list, hopefully we can get people to actually fix these old but useful issues
