### ISSUE TITLE
Aria2 options ? Or wget ?

### ISSUE THREAD

**Issue by Albnu14** [vn-ki/anime-downloader#242]
Hello my fellow otakus (^ ω ^) ,
Discovering this was the best thing that happened to me,
I was wondering if it is possible to use aria2 options or use another downloader like wget,
Right now I use dl command with -u option to get url then use wget or aria2 with wanted options.
If this is not implemented yet, don't worry about it things are already fine,
Arigatou *-*.

**Comment by andrewlef** [comment]
Aria2 can be used with options.  Just add them to the aria2 config file.

**Comment by Albnu14** [comment]
Thanks for your replg That is good and all, but it is not usable if I need one option for now and another one for another time where I edit the config file everytime I need a specific option,
It is not THAT important of a thing I'm happy enough downloading animes adfree. But it would be a good enhancement to add.

**Comment by vn-ki** [comment]
You can add it to the config file. You can use wget, aria2 or any other downloader.
