### ISSUE TITLE
Support ARM Devices

### ISSUE THREAD

**Issue by LiteracyFanatic** [vn-ki/anime-downloader#243]
Not a high priority feature by any means, but it would be neat if this worked on ARM devices like the Raspberry Pi 3. As far as I can tell, the requests_cache library is the only incompatible part. I don't do too much with python, so I'm just guessing, but I would figure it has to be some sort of bundled C code. Maybe related to the sqlite backend. I'm not sure if there would be an equivalent libarary that does work on ARM or perhaps just a configuration option that would allow the caching to be disabled on devices that don't support it.

```
$ uname -a
Linux mpd-server 5.3.6-1-ARCH #1 SMP Sat Oct 12 17:02:44 UTC 2019 aarch64 GNU/Linux
```

**Comment by hunkyburrito3** [comment]
I’m not sure if it helps any, but I think it might be possible as I have it running on my jailbroken iPhone 8 which runs on Debian Linux and is ARM64

**Comment by LiteracyFanatic** [comment]
Thanks. I managed to get it working with a single user install, so it's probably a packaging issue.
