### ISSUE TITLE
Installation instructions for macOS should be changed (temporarily?)

### ISSUE THREAD

**Issue by gingerbeardman** [vn-ki/anime-downloader#248]
**Describe the feature here**
Installation instructions for macOS should be changed (temporarily?)

https://github.com/vn-ki/anime-downloader/wiki/Installation

For macOS

Installation instructions say "use brew" then read a thread that says "do not use brew" see #205 

It would be great if "use brew" could be removed (temporarily?)

**Comment by vn-ki** [comment]
Someone has to update brew package. Since v4 is available at pypi, now might be a good time.

**Comment by vn-ki** [comment]
@nandahkrishna can you update the brew formula?

**Comment by nandahkrishna** [comment]
Sure I'll get that done.

**Comment by nandahkrishna** [comment]
Has 4.0.0 been "released" on GitHub? I need the archive to be available on GitHub to update the brew formula.

**Comment by vn-ki** [comment]
@nandhakrishna I'll do that today

**Comment by vn-ki** [comment]
@nandahkrishna Sorry for the delay. I have released 4.0.1.

Please make aria2 a dependency. Also 'cloudflare' option has been removed, so please note that too.

**Comment by nandahkrishna** [comment]
Alright, thanks!

**Comment by nandahkrishna** [comment]
PR for anime-downloader 4.0.1 has been submitted to homebrew-core.

**Comment by gingerbeardman** [comment]
Here for those that like to watch https://github.com/Homebrew/homebrew-core/pull/45722

**Comment by vn-ki** [comment]
Brew has been updated
