### ISSUE TITLE
list index out of range ( kissanime.ru )

### ISSUE THREAD

**Issue by clarychristionc** [vn-ki/anime-downloader#266]
**Describe the bug**

unable to download
getting error `list index out of range`
![Screenshot_2019-11-09_19-32-072](https://user-images.githubusercontent.com/47944263/68529871-e0834400-02fa-11ea-96cb-a4bfc1dba302.png)

and unable to print log
![Screenshot_2019-11-09_19-40-232](https://user-images.githubusercontent.com/47944263/68529863-cf3a3780-02fa-11ea-9df2-b14ae9bedfe0.png)

**To reproduce**

```
anime dl 'https://kissanime.ru/Anime/Mairimashita-Iruma-kun' --skip-download -e 2: -q 480p -xd "{aria2}"

anime dl 'https://kissanime.ru/Anime/Mairimashita-Iruma-kun' --skip-download -e 2: -q 480p -xd "{aria2}" -ll DEBUG
```

<details>
<summary>LOG</summary>

```



```

**Comment by voltrare** [comment]
Me too

**Comment by sirius16** [comment]
Idk about the rest, but the logging isn't working because you're putting the "-ll DEBUG" after everything else, but you have to put it right after "anime" and before "dl"
So, for instance 
`anime -ll DEBUG dl 'https://kissanime.ru/Anime/Mairimashita-Iruma-kun' --skip-download -e 2: -q 480p -xd "{aria2}"`

**Comment by BlackXDragon** [comment]
I have the same `list index out of range` problem.

**Comment by tolicon** [comment]
same story 
/Users/nikitos/Desktop/Снимок экрана 2019-11-21 в 17.42.14.png
/Users/nikitos/Desktop/Снимок экрана 2019-11-21 в 17.42.02.png
/Users/nikitos/Desktop/Снимок экрана 2019-11-21 в 17.41.50.png

**Comment by BlackXDragon** [comment]
Please help!

**Comment by nate-moo** [comment]
Update, also kissanime is broken

**Comment by Blatzar** [comment]
> Update, also kissanime is broken

Recorded in [FAQ](https://github.com/vn-ki/anime-downloader/wiki/FAQ). Will be fixed once [Selescrape](https://github.com/vn-ki/anime-downloader/pull/363) gets accepted (because of cloudflare).

**Comment by MichaelDavidJohnson** [comment]
KissAnime works now
