### ISSUE TITLE
Unicode error when downloading from 9anime

### ISSUE THREAD

**Issue by eggyrulz** [vn-ki/anime-downloader#268]
**Describe the bug**

I'm new to python and CL in general so its possible im just overlooking something super basic here, but whenever i attempt to use this program it returns a unicode error as seen in my log at the bottom. I've attempted about 3 different shows now all on 9anime server as it's the only one i know works for me in other downloaders, (albeit extremely slowly in them). my first attempt was a batch download for the entire show, ending in failure, my second was an attempt to download just the first episode, again failed, and here you can see what is my latest attempt where i gave up completely and came here for help.

Hopefully someone is able to help and the solution is simple. thank you.

**To reproduce**

```
anime -ll DEBUG dl 'shoumetsu toshi' --provider 9anime -xd "{aria2}"
Enter the anime no:  [1]: 2
```

<details>
<summary>LOG</summary>

```
https://pastebin.com/2Trv9iXG


```

**Comment by vn-ki** [comment]
9anime has captcha and is effectively dead.
