### ISSUE TITLE
python 3.8 and standard error redirection

### ISSUE THREAD

**Issue by RaitaroH** [vn-ki/anime-downloader#270]
**Describe the bug**

In adl I was using `anime dl OPTIONS 2> /dev/null` which I added to remove errors. Now that my system got updated to py3.8 though, it seems EVERYTHING that anime dl outputs is also redirected. Is this a bug, either with anime dl or python 3.8? 

**To reproduce**

This command:
```
anime dl 'vinland saga' --play mpv --episodes 1
```
gives this output:
```
anime: anime-downloader 4.0.1
+--------+--------------+--------+
|      1 | Vinland Saga |        |
|--------+--------------+--------|
|   SlNo | Title        | Meta   |
+--------+--------------+--------+
Enter the anime no:  [1]:
anime: Selected Vinland Saga
anime: Extracting episode info from page
anime: Found anime: Vinland Saga
```
But this:
```
anime dl 'vinland saga' --play mpv --episodes 1 2> /dev/null
```
returns nothing, even though it should just redirect stderr and not also stdout.

**Comment by vn-ki** [comment]
This is intended I guess. So that links can be exclusively redirected.
