### ISSUE TITLE
Weird Bug, what did i wrong ?

### ISSUE THREAD

**Issue by KoroFX** [vn-ki/anime-downloader#274]
![image](https://user-images.githubusercontent.com/46395233/71376966-92cd4d00-25c3-11ea-968b-d93e573b9aaa.png)
![image](https://user-images.githubusercontent.com/46395233/71376973-982a9780-25c3-11ea-99a2-8dbe0ad15506.png)

**Comment by vn-ki** [comment]
This has been fixed now.
