### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by ArjunAbhijith** [vn-ki/anime-downloader#275]
![image](https://user-images.githubusercontent.com/44577062/71449033-66543500-276b-11ea-9014-71ef9821340d.png)

command :--> anime -ll DEBUG watch 'fullmetal' --new

**Comment by RaitaroH** [comment]
I see you are using 9anime. That provider is broken.

I recommend to you is to change the provider in the config file to something like animepahe, or just use the `--provider animepahe` flag. Please take a look at PR https://github.com/vn-ki/anime-downloader/pull/279. You can also take a look at the issue I have linked in it as well.
