### ISSUE TITLE
Cache already fetched urls?

### ISSUE THREAD

**Issue by RaitaroH** [vn-ki/anime-downloader#278]
**Describe the feature here**
I was just using `adl` a bit and instead of making a range from 6 to 12 I made it from 7 to 12 and that made me wonder. Would be nice if adl had cached the urls retrieved for ep 7-12 so the next time when `anime dl` is called it could just fetch ep 6 url and append 7-12.

I have no idea how long is the `life` of usage of a fetched url. It could be one time use or forever, this is just an interesting suggestion :)

**Comment by vn-ki** [comment]
This has been fixed.
