### ISSUE TITLE
Error when running anime dl

### ISSUE THREAD

**Issue by terraenvy** [vn-ki/anime-downloader#280]
Hello!
Was looking for some assistance here.
I use this with Ubuntu headless Server
I have used this without issues in the past and have never had a problem, but recently I have been running into an issue where whenever I run the anime dl command I get the error 
ERROR: [Errno 2] No such file or directory: 'node' : 'node'

Any assistance would be appreciated.
![Capture2](https://user-images.githubusercontent.com/37300802/72196098-2cbe3380-33d3-11ea-93d0-a57e0c557d4e.JPG)

-Terra

Edit:
For more information, I had it working until one day this just started happening.
I use this in a Linux virtual machine and since I didn't need the machine anymore I created a new virtual machine that ONLY has Aria2, Python3, and Anime-Downloader on it.
So its a clean install that should have nothing getting in the way.

**Comment by RaitaroH** [comment]
You are using twist.moe. I am not sure on this, but as far as I am aware twist.moe never worked for me, most likely due to missing Node.js? I might be mistaken on that so what I recommend to you is to change the provider in the config file to something like animepahe. Please take a look at PR https://github.com/vn-ki/anime-downloader/pull/279. You can also take a look at the issue I have linked in it as well.

@vn-ki didn't answer me if this is a bug or just missing Node.js. Considering you are facing this issue my PR has even more reasons to be merged :)

**Comment by terraenvy** [comment]
> You are using twist.moe. I am not sure on this, but as far as I am aware twist.moe never worked for me, most likely due to missing Node.js? I might be mistaken on that so what I recommend to you is to change the provider in the config file to something like animepahe, or just use the `--provider animepahe` flag. Please take a look at PR #279. You can also take a look at the issue I have linked in it as well.
> 
> @vn-ki didn't answer me if this is a bug or just missing Node.js. Considering you are facing this issue my PR has even more reasons to be merged :)

It is definitely twist.moe.
Whats interesting is that It was literally overnight that it worked then didn't.
Looks like multiple require node.js as well.
animepahe does however seem to be working!
I appreciate the assistance on this as while I did see issues referencing the node.js issue, I did not find anything with my specific error. 
Appreciate it! :)

**Comment by terraenvy** [comment]
Correction, not working still
When using animepahe it at least lets me search for anime, but when trying to download it now tells me that.
Just to make sure I tried downloading an unrelated file using aria2 and it downloads with no issues.
![Capture3](https://user-images.githubusercontent.com/37300802/72223170-57220500-3529-11ea-910f-d154d371d97d.JPG)

**Comment by RaitaroH** [comment]
@terraenvy please take a quick look at https://github.com/vn-ki/anime-downloader/issues/282
It seems something on the animepahe side was off temporarely. Now it should be working for you :)

Also check out my https://github.com/RaitaroH/adl for a better `anime dl` experience.

**Comment by vn-ki** [comment]
Closing because this seems to be resolved.
