### ISSUE TITLE
Fallback providers

### ISSUE THREAD

**Issue by RaitaroH** [vn-ki/anime-downloader#281]
**Describe the feature here**
Resolution fallback is already a thing. Why not provider fallback? If the anime is not on that proivider, go to the next one. It will basically be what I've shown before as a script, but now it would be a feature. This would be a setting in the config file.
```
  adlwrap() {
    declare -a provider=(animepahe anistream animeflix animefreak gogoanime itsaturday animeflv kissanime kisscartoon twist.moe)
    for k in $provider; do
        printf "\n\033[0;31m%s\n" "PROVIDER: $k"
        anime dl "$1" --episodes "$2" --provider "$k" --play mpv; done
  }
```

**Comment by RaitaroH** [comment]
So if this is implemented then we don't need this: https://github.com/vn-ki/anime-downloader/issues/267 I will close that one in favor of this which seems to be a better implementation.

**Comment by vn-ki** [comment]
I think `anime test` would be enough for this? What do you think @RaitaroH ?

**Comment by RaitaroH** [comment]
I guess? The idea was something different though, but I am glad you didn't abandon this project.

**Comment by vn-ki** [comment]
Trying it for every provider will be slow. With `anime test` you can see which provider have the anime and select the provider you like.

**Comment by vn-ki** [comment]
Do you think this is enough for this issue to be closed?

**Comment by RaitaroH** [comment]
I suppose this will work out :)
