### ISSUE TITLE
Cant download anything, and this pops every time.

### ISSUE THREAD

**Issue by DmarZX2** [vn-ki/anime-downloader#283]
![wwwww](https://user-images.githubusercontent.com/60110135/72747055-0a939500-3bcd-11ea-8f51-717085dd62dc.PNG)

**Comment by Muhammad-Usman-Ali** [comment]
which server you use??
try with "anime dl" not with "anime -ll DEBUG dl"

**Comment by DmarZX2** [comment]
> which server you use??
> try with "anime dl" not with "anime -ll DEBUG dl"
I  Cant use "anime dl" with 9anime

**Comment by Muhammad-Usman-Ali** [comment]
9anime did not work at this time
and also I think"Kissanime and Kisscartoon" not work and twist.moe have some internel security so that also not work
try other like animepahe etc

**Comment by DmarZX2** [comment]
thanks, animepahe worked

مع السلامة...
