### ISSUE TITLE
Downloaded 480p not 720p why??????

### ISSUE THREAD

**Issue by uali6981** [vn-ki/anime-downloader#284]
I download "Nouryoku wa Heikinchi de tte Itta yo ne!" Ep 9 from anistream and selected 720p quality but downloaded instead in 480p something. I also check on other anime but 720p not download why????

and they also have 720p for anime.
check this
![Annotation 2020-01-21 220454](https://user-images.githubusercontent.com/56256581/72827690-12226f00-3c9d-11ea-9eed-6298534cbc13.png)

and for command I gave
![Annotation 2020-01-21 220954](https://user-images.githubusercontent.com/56256581/72827715-1fd7f480-3c9d-11ea-9b84-ee76eb0e8945.png)

and the ep download from this
![Annotation 2020-01-21 215408](https://user-images.githubusercontent.com/56256581/72827745-28c8c600-3c9d-11ea-87f4-73d98eb26b50.png)

**Comment by ngomile** [comment]
The downloader seems to be getting the link from trollvids, can you please check if the resolutions are different. On mp4upload it's a 1080p file not 720p and that's what IDM is showing you, not sure what it is on trollvids since my data is too constrained to even check but it may be 720p proper.

**Comment by Muhammad-Usman-Ali** [comment]
As for downloaded without giving any quality
![Annotation 2020-01-23 123811](https://user-images.githubusercontent.com/56256581/72965907-51f16f80-3ddf-11ea-93e6-8bb9ae5bec60.png)
![Annotation 2020-01-23 123623](https://user-images.githubusercontent.com/56256581/72965920-5cac0480-3ddf-11ea-8402-ca89882e6fa4.png)


and after giving "-q 1080p" in version "dubbed"
![Annotation 2020-01-23 124234](https://user-images.githubusercontent.com/56256581/72965975-7ea58700-3ddf-11ea-9bea-612e17a5bc1e.png)

and after giving "-q 1080p" in version "subbed"
![Annotation 2020-01-23 125033](https://user-images.githubusercontent.com/56256581/72965991-882eef00-3ddf-11ea-8c06-50514d06fade.png)

**Comment by ngomile** [comment]
I'm working on it, almost done.

**Comment by Muhammad-Usman-Ali** [comment]
Thanks.
and please check "Animepahe" problem occur after selecting anime like "kissanime"

**Comment by ngomile** [comment]
Okay I took longer than expected but I've made a pull request that sorts out some of the issues with anistream, there still may be some undiscovered pain points but I tried to at least make sure things are working okay. You should be able to get Nouryoku wa Heikinchi de tte Itta yo ne! now. #285 this is the pull request.

**Comment by Muhammad-Usman-Ali** [comment]
after updating "anistream.py" anime "mp4upload.py" problem remain same,

**Comment by Muhammad-Usman-Ali** [comment]
Ok
I will create other request for animepahe.
