### ISSUE TITLE
ERROR: 'NoneType' object has no attribute 'select'

### ISSUE THREAD

**Issue by WARHE8D** [vn-ki/anime-downloader#287]
![Capture](https://user-images.githubusercontent.com/59991459/73131852-4d73c380-4038-11ea-8f7f-88493dd19b07.PNG)

**Comment by Muhammad-Usman-Ali** [comment]
in which provider this error occur??
I think provider with "MP4UPLOAD" server. There are some problem with "MP4UPLOAD" server

**Comment by WARHE8D** [comment]
Yes it was from mp4upload. Can you please provide a solution for this error. Thank you

**Comment by Muhammad-Usman-Ali** [comment]
which server you use?

**Comment by WARHE8D** [comment]
Twist.moe? Tbh I’m new to programming so I don’t understand the programs. I just followed the tutorial from a YouTube video.

**Comment by Muhammad-Usman-Ali** [comment]
forget twist.moe.
Animepahe, Kissanime, Kisscartoon, twist.moe, 9anime
not work at this time
choose other

**Comment by Muhammad-Usman-Ali** [comment]
and type `anime dl --help` for full instruction about using `dl` command

**Comment by WARHE8D** [comment]
thank you so much. Also all the servers mentioned above are not working?
can you recommend me any alternating servers?
Again thank you very much for guiding me through these instructions

**Comment by Muhammad-Usman-Ali** [comment]
`anistream` `animefreak`

**Comment by Muhammad-Usman-Ali** [comment]
please tell me whats your python version

**Comment by WARHE8D** [comment]
![a](https://user-images.githubusercontent.com/59991459/73132790-bf9ed500-4045-11ea-86c9-31f7ef9f3c85.PNG)
i need to install cfscrape
i`ll download it rn

**Comment by Muhammad-Usman-Ali** [comment]
Simply run `pip install cfscrape`. You can upgrade with `pip install -U cfscrape`.

Alternatively, clone this repository `https://github.com/Anorov/cloudflare-scrape` and run `python setup.py install`.

**Comment by Muhammad-Usman-Ali** [comment]
did you install `Chocolatey Package manager`?

**Comment by WARHE8D** [comment]
![s](https://user-images.githubusercontent.com/59991459/73132874-f6291f80-4046-11ea-8c7f-e0da2046121d.PNG)
new error!?

**Comment by WARHE8D** [comment]
no i havent installed choco

**Comment by WARHE8D** [comment]
ihav installed choco.

**Comment by Muhammad-Usman-Ali** [comment]
ok first delete `anime-downloader` folder and then open `cmd` with `Run as administrator` and put this code `choco install -y git python3 aria2 mpv nodejs`. After installing these put this code where you want to install this code `pip install git clone https://github.com/vn-ki/anime-downloader` and after that put `pip install -e .` and after that install `cfscrape`.
All done

**Comment by Muhammad-Usman-Ali** [comment]
and also give `PATH` to all these `node, python, MPV, choco, git, aria2`

**Comment by Muhammad-Usman-Ali** [comment]
sorry. I forget `choco` after deleting folder `powershell` with `Run as administrator` and put this code `Get-ExecutionPolicy. If it returns Restricted, then run Set-ExecutionPolicy AllSigned or Set-ExecutionPolicy Bypass -Scope Process` and after this run cmd like I said before.

**Comment by WARHE8D** [comment]
should i just delete anime-downloader or the other things like choco and cfscrape too?
i have already installed them

**Comment by Muhammad-Usman-Ali** [comment]
If error appear again like above then you should do that.
`PATH` is very important

**Comment by voltrare** [comment]
i think sometimes mp4upload is blocked by your internet provider
because it happens with me
i tried using vpn
