### ISSUE TITLE
Getting `anime: command not found` after install on ubuntu

### ISSUE THREAD

**Issue by rizkymeiputra** [vn-ki/anime-downloader#309]
Hello!
I just installed anime-downloader on ubuntu using pip install
But I keep getting `anime: command not found` when I want to run it
I try to find out what happens, and some of that said you need to go the PATH or directory but I don't know where is exactly the directory
Thanks
![Screenshot from 2020-03-26 00-21-34](https://user-images.githubusercontent.com/48079559/77566353-1b77c400-6ef8-11ea-87e7-05c0473919e5.png)

**Comment by Blatzar** [comment]
To get path type: `echo $PATH`
First find the anime executable (mine is located in /usr/bin/anime) and add that directory to your path, for me it would be /usr/bin, to add I'd do: `PATH=$PATH:/usr/bin`

**Comment by rizkymeiputra** [comment]
I just restart my machine and it's work lol
Thanks a lot for your reply @Blatzar
