### ISSUE TITLE
Default file hoster 

### ISSUE THREAD

**Issue by FarlsBarkley** [vn-ki/anime-downloader#32]
I was testing out the anime dl function on 9anime when I noticed that the default source is RapidVideo. Is there any way that the source can be changed? RapidVideo is nice since it has quality options, but the other sources are far more consistent with quality.

**Comment by vn-ki** [comment]
It is not available right now, but I am currently planning to add it.

I did not add it before because the stream url extraction was a mess. I recently did a [refractor](https://github.com/vn-ki/anime-downloader/commit/a289f72ee6c3ec732f563913ed2496fc8f17d208) which makes the whole process a lot easier to use and maintain.

**Comment by vn-ki** [comment]
@FarlsBarkley I looked into it and openload uses js obfuscation which makes it hard to get the url. The sources fail to load for me.

I don't think it's worth the effort as rapidvideo has quality options which the other sources lack. Rapidvideo performs better on my internet too. Do you have any strong arguments for other sources or any against RapidVideo? If you have some good arguments, I can look into it.

**Comment by FarlsBarkley** [comment]
No strong arguments against Rapidvideo, what I posted about before can easily be solved on their end.

**Comment by vn-ki** [comment]
I would still like to keep it open. I'll come back to this if I get time.

**Comment by vn-ki** [comment]
An options json object in config or as a cmd line argument can be used to do this

**Comment by KnineVspython** [comment]
Can I use this api to make a steaming website

**Comment by vn-ki** [comment]
Technically yes, but I don't think it makes a lot of sense to do that. Also, the current state of free anime streaming is pretty shitty.

**Comment by KnineVspython** [comment]
Yeah that what I was thinking make a steaming website that’s not ugly and
ads everywhere

**Comment by KnineVspython** [comment]
I was looking for api that I can use that I don’t  manually need to add new
episodes and stuff

**Comment by vn-ki** [comment]
This is now fixed in master
