### ISSUE TITLE
wakanim.tv implementation

### ISSUE THREAD

**Issue by ScarVite** [vn-ki/anime-downloader#338]
Would be amazing if you could implement wakanim 
https://www.wakanim.tv/

**Comment by MichaelDavidJohnson** [comment]
Website doesn't work for every country, so I'm not going to work on it. Unless someone wants to hard code in a vpn inside anime-downloader.

**Comment by ScarVite** [comment]
i found this. 
Do you think this might be able to work?
https://stackoverflow.com/questions/35144685/how-to-vpn-proxy-connect-in-python

**Comment by MichaelDavidJohnson** [comment]
The example is accessing a proprietary VPN inside Python. It still requires the user the be paying for one. The only way to fully avoid that would be for us to make our own private server, which is unfeasible especially when so many sites already work pretty well.

**Comment by Blatzar** [comment]
Too much effort for too little payoff in my opinion
