### ISSUE TITLE
Subtitle provider.

### ISSUE THREAD

**Issue by ArjixGamer** [vn-ki/anime-downloader#343]
**Describe the feature here**
So, if we add raw providers, i suggest making a subtitle provider that gets the subtitles for the requested episode and language. that way we can use 1 anime provider for multiple languages.
My current suggestion is [opensubtitles](https://www.opensubtitles.org/) since its the best subtitle website for anime. Nut there is a limit to how many subs you can download as a free user per day.

**Comment by LagradOst** [comment]
I dont have a problem with "there is a limit to how many subs you can download as a free user per day." There is a easy way to bypass that. You can directly use IMDb episode id for to download subtitles, so if you manage to link the search to IMDb you are golden. But in general, the subtitles are from the sub and dosent match the dub. Also not that many anime have subtitles on opensubtitles, it is best used for movies.

**Comment by nate-moo** [comment]
I hath been called upon.
but I think my name be used in the wrong context

**Comment by vn-ki** [comment]
In which scenario is this useful?

**Comment by MichaelDavidJohnson** [comment]
I definitely think a subtitle provider is completely out of the scope of the project.

**Comment by AbdullahM0hamed** [comment]
I agree with @MichaelDavidJohnson on this.

**Comment by MichaelDavidJohnson** [comment]
Does anyone have a valid reason for keeping this issue open? I'll close at EOD if there's no development.

**Comment by Blatzar** [comment]
Subtitles for the few movie providers we have wouldn't hurt, but I'm not saying that I'll be the one picking up that.

**Comment by Blatzar** [comment]
Nvm I see the other comments, it's chill to close

**Comment by MichaelDavidJohnson** [comment]
Out of the scope of the project.
