### ISSUE TITLE
KissAnime Hydrax support

### ISSUE THREAD

**Issue by Soldat56** [vn-ki/anime-downloader#351]
From what I have read, KissAnime support has been dropped because of their Rapid seven drop. They now also use Hydrax which permits bypass of the captcha.

I'm not sure if this will help, though, because I tried to get stream url of Hydrax player and did not manage to find anything.

**Comment by Blatzar** [comment]
https://github.com/vn-ki/anime-downloader/issues/2#issuecomment-620438597
