### ISSUE TITLE
Output download links without downloading

### ISSUE THREAD

**Issue by Miosame** [vn-ki/anime-downloader#354]
It would help a lot to those of us who use other means of downloading, if there would be some sort of `--output` flag - that simply returns all the links to console, including either through the same menu'esque selection prior or by directly giving it a e.g. kissanime link.

**Comment by AbdullahM0hamed** [comment]
There is the `-u` flag. Like so: `anime dl -u "Naruto"`

**Comment by ArjixGamer** [comment]
wtf, if you want the direct link to the episode then add the -u flag. It will output the link to the console/terminal
> anime do "overlord III" -e 13 -u

**Comment by ArjixGamer** [comment]
And also before requesting features check before if they already exist.
There is a help command.
> anime dl --help

**Comment by Miosame** [comment]
Thanks!
