### ISSUE TITLE
Kisscartoon not working with Provider command ( Kissanime works )

### ISSUE THREAD

**Issue by Jtgroos** [vn-ki/anime-downloader#36]
@vn-ki 
i found this when trying to use the downloader to download cartoons from kisscartoon

X:\>anime dl --provider KissCartoon "winx"
Usage: anime dl [OPTIONS] ANIME_URL

Error: Invalid value for "--provider": invalid choice: KissCartoon. (choose from 9anime, kissanime)

--------------------

Kissanime does work:
X:\>
X:\>anime dl --provider kissanime "no souma"
[32manime[0m: anime-downloader 3.1.1
 1: Food Wars! The First Plate (Dub)

**Comment by vn-ki** [comment]
KissCartoon provider has not been implemented yet. Honestly I never thought someone would ever use KissCartoon. I'll work on it.

**Comment by Jtgroos** [comment]
Haha yeah not many will but my family always asks me for older kid shows like winx so you was really happy to see that you had both.

happy to see you shall work on it ( no hurrys needed tho take your time )

**Comment by Enderlein** [comment]
Started working on this.
So far, got the search results to work. I'll begin working on watching and downloading tomorrow.

**Comment by vn-ki** [comment]
This has been fixed.
