### ISSUE TITLE
Error when downloading file that already exists

### ISSUE THREAD

**Issue by tzulberti** [vn-ki/anime-downloader#377]
**Describe the bug**
The message says that the file isn' t going to be downloaded but it download it again nevertheless

**To reproduce**
```
INFO:anime_downloader.sites.anime:Downloading aa-megami-sama-sorezore-no-tsubasa-1
anime: ./aa-megami-sama-sorezore-no-tsubasa/aa-megami-sama-sorezore-no-tsubasa_01.mp4
INFO:anime_downloader.downloader.base_downloader:./aa-megami-sama-sorezore-no-tsubasa/aa-megami-sama-sorezore-no-tsubasa_01.mp4
anime: File already downloaded. Skipping download.
WARNING:anime_downloader.downloader.base_downloader:File already downloaded. Skipping download.
anime: Using internal downloader which might be slow. Use aria2 for full bandwidth.
WARNING:anime_downloader.downloader.http_downloader:Using internal downloader which might be slow. Use aria2 for full bandwidth.
Downloaded: 172.09MB/171.91MB, Rate: 521.72KB/s
```

**Comment by ArjixGamer** [comment]
em, i dont know where the bug here is but, try to use aria2. if the file already exists aria2 by default skips it so until this bug is fixed i suggest you use aria2

**Comment by tzulberti** [comment]
The logging message says:
```
WARNING:anime_downloader.downloader.base_downloader:File already downloaded. Skipping download.
```

But it still downloads the file. I have check using aria2, but on Ubuntu I am having some issues. I have to spend some more time with that

**Comment by Blatzar** [comment]
The internal downloader isn't very good or supported, as Arjix said I recommend you use aria2c. Remember to activate it in config like this `"external_downloader": "{aria2}",`
