### ISSUE TITLE
Kissanime is not working.

### ISSUE THREAD

**Issue by phanirithvij** [vn-ki/anime-downloader#40]
**Describe the bug**

Fails to extract Info from the page in KissAnime

**To reproduce**
```shell
anime dl "http://kissanime.ru/Anime/Gintama-Shirogane-no-Tamashii-hen-2/Episode-354?id=147594&s=rapidvideo" -ll DEBUG
```

**Log**
```shell
INFO root: anime-downloader 3.1.1
DEBUG root: Platform: Linux-4.8.0-53-generic-x86_64-with-LinuxMint-18.2-sonya
DEBUG root: Python 3.5.2
INFO root: Extracting episode info from page
'NoneType' object has no attribute 'text'

```

**Comment by phanirithvij** [comment]
```python
KissAnime = get_anime_class("http://kissanime.ru/Anime/Gintama-Shirogane-no-Tamashii-hen-2/Episode-354?id=147594&s=rapidvideo")

onepiece = KissAnime("http://kissanime.ru/Anime/One-Piece/Episode-844?id=147580")

print(onepiece)

```


    ---------------------------------------------------------------------------

    AttributeError                            Traceback (most recent call last)

    <ipython-input-6-a7526f558fdb> in <module>()
          1 KissAnime = get_anime_class("http://kissanime.ru/Anime/Gintama-Shirogane-no-Tamashii-hen-2/Episode-354?id=147594&s=rapidvideo")
          2 
    ----> 3 onepiece = KissAnime("http://kissanime.ru/Anime/One-Piece/Episode-844?id=147580")
          4 
          5 print(onepiece)


    /usr/local/lib/python3.5/dist-packages/anime_downloader/sites/anime.py in __init__(self, url, quality, _skip_online_data)
         36         if not _skip_online_data:
         37             logging.info('Extracting episode info from page')
    ---> 38             self.get_data()
         39 
         40     @classmethod


    /usr/local/lib/python3.5/dist-packages/anime_downloader/sites/baseanimecf.py in get_data(self)
         18         soup = BeautifulSoup(r.text, 'html.parser')
         19 
    ---> 20         self._scrape_metadata(soup)
         21 
         22         self._episode_urls = self._scarpe_episodes(soup)


    /usr/local/lib/python3.5/dist-packages/anime_downloader/sites/kissanime.py in _scrape_metadata(self, soup)
         98     def _scrape_metadata(self, soup):
         99         info_div = soup.find('div', {'class': 'barContent'})
    --> 100         self.title = info_div.find('a', {'class': 'bigChar'}).text
    

    AttributeError: 'NoneType' object has no attribute 'text'

**Comment by vn-ki** [comment]
You have to provide the url which contains the episode info, meaning the root anime page. This is true for all providers.

In this case,
```
anime dl "http://kissanime.ru/Anime/Gintama-Shirogane-no-Tamashii-hen-2/"
```
