### ISSUE TITLE
Aria2C error

### ISSUE THREAD

**Issue by Genxster1998** [vn-ki/anime-downloader#42]
nime: anime-downloader 3.1.1
 1: Plastic Memories

Enter the anime no:  [1]: 1
anime: Selected Plastic Memories
anime: Extracting episode info from page
anime: Found anime: Plastic Memories
anime: Downloading to /sdcard/Anime
anime: Downloading episode 1 of Plastic Memories
Specify at least one URL.
Usage: aria2c [OPTIONS] [URI | MAGNET | TORRENT_FILE | METALINK_FILE]...
See 'aria2c -h'.
In config ,I put kissanime and aria2c respectively .
Using Termux android
9anime works without aria2

_Sent from my Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by vn-ki** [comment]
You have to do `-xd "{aria2}"` to use the built in. 

If you want your own command you can do `-xd "aria2c {stream_url}"`. But I suggest you use the internal one as it has been configured to by pass throttling.

**Comment by Genxster1998** [comment]
Wow ,you are online and fast ,I already seen your answer in other issues ,so new error
