### ISSUE TITLE
Aria2 error

### ISSUE THREAD

**Issue by Genxster1998** [vn-ki/anime-downloader#43]
e: anime-downloader 3.1.1
 1: Plastic Memories

Enter the anime no:  [1]: 1
anime: Selected Plastic Memories
anime: Extracting episode info from page
anime: Found anime: Plastic Memories
anime: Downloading to /sdcard/Anime
anime: Downloading episode 1 of Plastic Memories

07/11 23:34:32 [NOTICE] Downloading 1 item(s)
[#1c697d 0B/0B CN:1 DL:0B]
07/11 23:34:34 [ERROR] CUID#7 - Download aborted. URI=https://www511.playercdn.net/173/0/zj-PeVxszB2s3GwU9P863A/1531353872/170427/Mfl2V9pcNI2CH3r.mp4
Exception: [/home/fornwall/.termux-build/aria2/src/src/AbstractCommand.cc:351] errorCode=1 URI=https://www511.playercdn.net/173/0/zj-PeVxszB2s3GwU9P863A/1531353872/170427/Mfl2V9pcNI2CH3r.mp4
  -> [/home/fornwall/.termux-build/aria2/src/src/SocketCore.cc:1015] errorCode=1 SSL/TLS handshake failure: hostname does not match

07/11 23:34:34 [NOTICE] Download GID#1c697da02286a59f not complete: /sdcard/Anime/Plastic_Memories/Plastic_Memories_1.mp4

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
1c697d|ERR |       0B/s|/sdcard/Anime/Plastic_Memories/Plastic_Memories_1.mp4

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.

This error also persist without aria2 , with inbuilt dwnloader

anime: Downloading Plastic Memories-1
anime: /sdcard/Anime/Plastic_Memories/Plastic_Memories_1.mp4
anime: Certificate did not match expected hostname: www511.playercdn.net. Certificate: {'subject': ((('organizationalUnitName', 'Domain Control Validated'),), (('organizationalUnitName', 'EssentialSSL Wildcard'),), (('commonName', '*.geokaps.com'),)), 'issuer': ((('countryName', 'GB'),), (('stateOrProvinceName', 'Greater Manchester'),), (('localityName', 'Salford'),), (('organizationName', 'COMODO CA Limited'),), (('commonName', 'COMODO RSA Domain Validation Secure Server CA'),)), 'version': 3, 'serialNumber': 'C2A2F4569BC4511FCBDCB12861A0A451', 'notBefore': 'Jun 23 00:00:00 2018 GMT', 'notAfter': 'Sep 21 23:59:59 2019 GMT', 'subjectAltName': (('DNS', '*.geokaps.com'), ('DNS', 'geokaps.com')), 'OCSP': ('http://ocsp.comodoca.com',), 'caIssuers': ('http://crt.comodoca.com/COMODORSADomainValidationSecureServerCA.crt',), 'crlDistributionPoints': ('http://crl.comodoca.com/COMODORSADomainValidationSecureServerCA.crl',)}
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/urllib3/connection.py", line 376, in connect
    _match_hostname(cert, self.assert_hostname or hostname)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/urllib3/connection.py", line 386, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/data/data/com.termux/files/usr/lib/python3.6/ssl.py", line 327, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
ssl.CertificateError: hostname 'www511.playercdn.net' doesn't match either of '*.geokaps.com', 'geokaps.com'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www511.playercdn.net', port=443): Max retries exceeded with url: /173/0/FrajYf_5UfNhi9_0zX-rKA/1531355552/170427/Mfl2V9pcNI2CH3r.mp4 (Caused by SSLError(Certificate

Continued...
_Sent from my Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_  

_Sent from my Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by vn-ki** [comment]
I cannot reproduce this. Are you sure you can download stuff through aria2 in termux?

Can you try downloading a generic video, maybe try this,
```
aria2c http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4
```

**Comment by vn-ki** [comment]
Also can you try the termux api downloader?

```
anime dl <whatever> -xd "termux-download {stream_url}"
```

Maybe we're lucky and it might work. :sweat_smile:

**Comment by vn-ki** [comment]
I tried this on my android phone and it works! Downloading with aria2 works. 

Can you try downloading from nineanime, instead of kissanime, just to make sure.

**Comment by Genxster1998** [comment]
nope all give same ssl issue with aria 2 .Flashed AICP , will check in this os.

**Comment by vn-ki** [comment]
I have AOSP Extended and I can download without any problems.

Can you try,
```
aria2c http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4
```
to make sure this is not a problem with the tool?

**Comment by Genxster1998** [comment]
OK ,can you tell me how to download specific episodes like 11,12,13-18 and 35-30

**Comment by vn-ki** [comment]
Did it work? 

Downloading is mentioned in the [wiki](https://github.com/vn-ki/anime-downloader/wiki/dl-command).

For,
- 11 : `-e 11`
- 13-18: `-e 13:19`
