### ISSUE TITLE
ERROR: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by Shalmon123** [vn-ki/anime-downloader#433]
Every time i use the command to download an episode it spits out this error.
full log : 
anime dl 'https://animepahe.com/anime/fullmetal-alchemist-brotherhood' --episodes 1anime: anime-downloader 4.3.0
anime: Extracting episode info from page
anime: Found anime: Fullmetal Alchemist: Brotherhood
ERROR: 'NoneType' object has no attribute 'groups'
Is there a  way to fix this? I followed the installation guide precisely.

**Comment by Blatzar** [comment]
Provider issue, see https://github.com/vn-ki/anime-downloader/issues/412
Check (FAQ)[https://github.com/vn-ki/anime-downloader/wiki/FAQ] for info on providers
