### ISSUE TITLE
nineanime.py error

### ISSUE THREAD

**Issue by Faizaan85** [vn-ki/anime-downloader#44]
**Describe the bug**
Download error when downloading from 9anime.is. It was downloading fine till 12 hr ago.

**To reproduce command used below**
anime dl https://www7.9anime.is/watch/one-piece-dub.34r/0vmw79 --episodes 380:401 --quality 360p --log-level DEBUG

<details>
<summary>LOG</summary>
INFO root: anime-downloader 3.1.1
DEBUG root: Platform: Windows-10-10.0.17134-SP0
DEBUG root: Python 3.7.0
INFO root: Extracting episode info from page
DEBUG root: data-ts: 1531382400
DEBUG root: EPISODE IDS: length: 572, ids: ['v07k4l', 'q37rr5', 'y6wn3z', '1wz61p', '5m1ln9', 'xz240v', '8p1oqy', 'j0wxk3', 'l21zm6', '4lwmlx', 'xz24ow', '0v07vr', 'p1wq19', '4lwk0j', 'j0wx73', 'k09y76', 'm83nz8', 'n0w17j', 'p1w97x', 'm83nz7', 'v07ko6', 'xz24x3', 'y6wnx1', '1wz65q', '3k9j59', 'm8380z', 'n0w018', 'o04028', 'p1w196', 'l2xmz3', 'q37343', '8p2qoo', 'r0305q', '3k0lw6', 'v070k4', 'wzwzl4', 'xz2zmq', 'y6w6nx', 'zzwzop', '0v0v5k', '1wzw6m', '2jwj7l', '3k9kj2', '4lwlkk', '5m1ml0', '6n1n29', '7o1o4j', '8p1p6n', '9q1q80', 'j0w0o2', 'k090q9', 'l212vn', 'm838xz', 'n0w0z8', 'o04018', 'p1w136', '3k9188', 'q37353', 'r0307q', 'l21y5z', 'v070p4', 'wzwzr4', 'xz2zwq', 'y6w6yx', 'zzwz0p', '0v0vnk', 'xz1qpz', '1wzwpm', '2jwjrl', '3k9kw2', '4lwlyk', 'r03yvy', '5m1m00', '6n1499', 'k0x7w9', '6n1zop', '3k0zr2', '7o19mj', '8p14kn', 'j0w8n2', 'k09jo9', 'l21kpn', 'm83lmz', 'n0wmn8', 'p1wok6', 'r03qmq', 'xz1qjq', 'y6w01x', '1wz42m', '4lw4rk', 'l2x7rn', '5mwj90', '6n14l9', 'j0w8v2', 'j0w8v3', 'n0wm3m', 'p1worq', 'v0qoq4', 'wzw017', 'zzw6lm', '3k947r', '5m17k9', '9q142m', 'l21k36', 'j027w2', 'o04no5', 'r03qjn', 'xz20j3', '0v04r5', '3k94pr', '4lw42j', '5m1799', '6n14w0', '9q140m', 'm83lv8', 'p1wopq', 'v07x9l', 'y6w0vz', 'r0ok3n', '9qjnym', '1wz4qp', '5m17w9', 'rqlz9q', '7o1901', 'j0w823', 'p1womq', 'wzw0q7', 'j027z3', 'y6w0jz', '1wz47p', 'y6jr8z', 'l2x7y6', '4lw4wj', '7o1911', '9q141m', 'k09j94', 'm83l38', 'zzw65l', '4lw4xx', '9q14yq', 'l21knm', 'p1wo4x', 'r03qrp', 'xz20xw', 'zzw68l', '0vmwo5', '3k94v9', '6n14jz', 'j02763', '9q14mq', 'o04374', 'l21k8m', 'n0wm4j', '2j7xj0', 'r03q4p', 'wzw08l', '9qjn3q', 'zzw6ql', 'y6jr61', '1wz49q', '4lw4zx', 'm8j787', '7o19zy', 'j0w838', 'm83ly7', '1wz9xx', 'o04n3y', '3k0z49', 'r03qyp', 'v07xm6', 'm83y1v', 'y6w091', 'xz1q0w', '1wz4yq', 'k0x766', '0vmw79', 'p1m7q9', 'l2x77q', '8p2m5q', '5mwj6m', 'v0qo37', '4lw49x', 'p1m7vj', 'k0x7nv', '9qjnvx', '6n0k57', '1w7x6x', 'p1m734', 'o0lk94', '7o19yy', '9q147q', 'k0xzww', 'l21k4m', '6n07lp', 'j0w86y', 'l21k4q', 'o04n8z', 'q37p25', 'v07xjv', 'xz19jq', 'q3zmn3', 'l2x0xn', '6n0719', 'y6jxwx', 'l2x0n6', '9qj5mm', 'q3zm8j', 'm8j148', 'k0xz16', 'y6jx01', 'wzqv0l', 'wzqv3l', 'm8j1np', 'l2x07q', '6n0774', '1w758v', 'y6jx7j', 'n0kjqn', '8p25wv', '2j05l4', 'wzqvj6', 'p1ml9j', 'm8j10x', '1w75px', 'v0qln2', 'o0lyj4', 'm8jwqv', 'k0xr3w', '4l162k', '0vm6mk', 'o0ly48', '9qj6y0', '8p29ln', '2j06q2', 'zzkpqm', 'p1mz2q', 'n0kx6m', '9qj6qm', 'xz1nzw', 'wzqm0l', 'm8jw57', '7o07py', 'zzkpvl', 'm8jw7p', '8p295q', '6n0664', '2j06mq', 'wzqm2o', 'j02qm4', '9qj6vx', '2j0614', 'o0ly2j', '4l16km', 'r0o17o', 'k0xrqv', 'zzk7r3', 'v0q3v2', 'l2xq33', '7o0rw6', 'y6j7v0', 'k0xpx9', '5mwpw0', '4l1owk', 'v0q3y4', 'l2xq8n', '4l1ovk', 'r0ozyn', '9qjw7m', 'zzk72m', 'o0lw65', '4l1olj', 'v0q30l', '9qjw4m', 'o0lwny', '4l1o8x', 'p1mx5x', '7o0rpy', 'v0q3z6', '8p2vm3', 'wzq7pl', 'j029y8', '1w7l8v', 'r0ozzm', 'j0299y', '6n0qr4', 'zzk79w', 'o0lwzj', '5mwp4j', 'v0q3k7', '4l1okm', 'p1mx3j', '2j0mr4', 'r0oxmo', 'k0xnov', 'zzkjl3', 'o0lro4', '5mwqkq', 'r0oxwy', '8p2wxo', 'xz131z', 'j02mwn', 'q3zw73', '6n0rx9', 'xz13xq', '8p2wln', '5mwqv0', 'q3zw83', 'm8jp48', 'l2xo66', 'm8jp88', 'j02m83', 'l2xo56', '9qjxrq', 'j02m78', '9qjx5q', '4l1p6x', 'v0q13v', 'r0oxxm', 'p1mvv9', '4l1pn7', 'v0q16v', 'j02mry', 'y6w0mj', 'r0ox5o', 'j02mx4', 'zzkj02', 'l2xovz', '1w7k2w', 'l2xjpz', 'y6jzqp', 'j024jn', '0vmjr7', 'v0qw92', 'r0opoy', 'v0qw72', 'j024l2', 'o0lmv8', 'l2xjyn', 'l2xj4n', 'l2xj6n', '5mwom9', '7o0q91', '4l1n8j', '1w7k1p', 'q3zorw', 'n0kl7j', 'p1mnlx', 'v0qwl6', 'r0opxm', 'v0qwwv', 'zzk9mw', '5mwolm', '2j0lr4', '3k02q8', '2j01o4', '4l13jm', '0vmzq7', '1w707x', '4l13wo', '2j01x5', '0vmzxk', '2j01ql', '2j01zl', '8p2jpn', '1w70wp', '4l138j', '5mw4n9', '3k02zr', 'xz1kqw', '3k0269', '9qjkwq', 'j02rmy', 'v0q66v', 'n0kyyl', 'y6jlyj', '0vm5p3', 'zzkol2', '2j0794', '6n0mw7', '2j7j95', '9qjp18', 'j02xzn', 'm8j0yv', 'l2xz4n', 'n0k168', 'n0k108', 'p1m9oq', 'o0l255', 'zzko4m', 'y6jnrz', 'o0l2ky', 'l2xz9m', 'k0xyp6', 'l2xzom', '7o0nqy', 'zzkomw', 'q3z415', 'k0xyyr', 'j02xoy', '6n0294', 'zzk0l2', 'wzqro6', 'xz1wv8', 'v0qpq7', 'l2xv13', '7o0416', '6n02xp', '0vmnx7', 'y6jyp0', 'p1m326', 'm83ywv', 'l2xv6n', 'j02o02', '7o049j', 'r0o7qq', '7o048j', 'wzqr37', 'o0l1p5', 'l2xv76', 'l2xv06', 'j02oq3', '2j0rm0', 'wzqr7l', 'y6jyz1', 'y6jyl1', 'n0kzyl', 'o0l12z', 'q3z555', 'zzwrlw', 'm83m2x', 'j0wnj4', '6n19w7', '3k9q08', '3k9q98', 'r03mry', 'q37lvv', 'k09o8w', 'n0wn2k', 'l21p6n', 'l21p2n', 'o049n8', 'n0wn58', 'l21pmn', 'k09o74', 'k09oz4', 'xz2pn3', 'wzw97l', '0v0pjr', '4lwr3x', '8p1ko3', '5m1r0m', '6n1l94', '3k9rry', '9q1o2n', 'y6wqvp', 'wzw1q6', '0v0439', '3k943y', '5m173m', '8p143q', 'xz2r28', 'k09j1r', 'm83l6p', 'q37p65', '0v0o67', 'wzw0zo', '2jw4jq', '4lw4l7', '6n14n4', '9q14qn', 'k09j0r', 'r03lro', 'n0wm0l', 'p1wo19', 'q37p35', 'j0wvzn', 'r03qqm', 'v07xxv', 'k09w8w', 'wzw00o', '8p10zo', '7o1jy6', '7o1j36', '0v02vk', 'xz200v', 'y6w00j', 'zzw66w', 'y6wq0x', 'p1wr56', '0v0449', '1wz44v', '2jw44q', 'p1wrq6', 'k09w79', '3k944y', '4lwq5j', '2jwo62', '4lw447', 'xz2rn3', 'l21lq6', '5m12q9', 'r03lxp', '7o1jqy', '2jwo10', 'xz2rkw', 'n0w31j', 'j0wvo8', 'y6wk1j', 'v075vv', 'n0wr3l', '3k977y', 'v0759v', '6n1vw4', 'p1wjmj', '3k9708', 'r03j3o', '5m1k1j', 'v075y7', 'k09kmv', '6n1vj7', 'xz2joz', 'l21343', '4lwj9o', 'p1wj64', '9q1238', '2jw9j5', 'm83qlz', '4lwj4k', 'xz2j5q', 'k09kl9', '7o1wlj', '2jw9yl', 'n0wrjm', '5m1k69', 'xz2jn3', 'n0wrvm', 'zzw1jm', 'n0wrlj', '3k9729', 'v07566', 'l213zm', '9q128q', 'm83vm7', '7o12j8', '1wzqrv', 'n0wprl', '7o1228', 'xz2v1v', 'n0wpwn', '7o1217', '4lw2xm', 'xz2v88', 'xz2vo8', 'k0934w', '6n1wyp', '0v0q37', 'm83v8v', '4lw2lo', 'v079x2', '7o1296', 'm83v5z', 'k0k2jv', '3k7v88', 'v05847', 'o0ov5j', 'j0jz04', '7owk97', 'l2346q', '2j9zz0', '9q277q', 'k0k44r', '8pn73q']
INFO root: Found anime: One Piece (Dub)
INFO root: Downloading to Y:\TV\One Piece
DEBUG root: Extracting stream info of id: 2j7j95
DEBUG root: API call URL: https://9anime.is/ajax/episode/info with params {'id': '2j7j95', 'server': '33', 'ts': '1531382400', '_': 674}
DEBUG root: URL: https://www8.9anime.is/ajax/episode/info?id=2j7j95&server=33&ts=1531382400&_=674
DEBUG root: Returned data: {'error': 'token'}
DEBUG root: API call URL: http://9anime.cloud/ajax/episode/info with params {'id': '2j7j95', 'server': '33'}
DEBUG root: URL: http://9anime.cloud/ajax/episode/info?id=2j7j95&server=33
DEBUG root: Returned data: {'error': 'token'}
Traceback (most recent call last):
  File "c:\python\lib\site-packages\anime_downloader\sites\nineanime.py", line 33, in _get_sources
    url = get_stream_url(self._base_url, params)
  File "c:\python\lib\site-packages\anime_downloader\sites\nineanime.py", line 30, in get_stream_url
    return data['target']
KeyError: 'target'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python\lib\site-packages\anime_downloader\sites\nineanime.py", line 42, in _get_sources
    url = data['target']
KeyError: 'target'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Scripts\anime.exe\__main__.py", line 9, in <module>
  File "c:\python\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\python\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\python\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\python\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\python\lib\site-packages\anime_downloader\cli.py", line 113, in dl
    for episode in anime:
  File "c:\python\lib\site-packages\anime_downloader\sites\anime.py", line 74, in __getitem__
    ep_no=ep_id[0])
  File "c:\python\lib\site-packages\anime_downloader\sites\anime.py", line 118, in __init__
    self.get_data()
  File "c:\python\lib\site-packages\anime_downloader\sites\anime.py", line 152, in get_data
    self._sources = self._get_sources()
  File "c:\python\lib\site-packages\anime_downloader\sites\nineanime.py", line 48, in _get_sources
    ) from e
anime_downloader.sites.exceptions.AnimeDLError: 9anime probably changed their API again. Check the issueshere https://github.com/vn-ki/anime-downloader/issues. If it has not been reported yet, please open a new issue
</details>

**Comment by vn-ki** [comment]
Update and you should be good to go.
