### ISSUE TITLE
Add 4anime.to

### ISSUE THREAD

**Issue by SelectLOL1** [vn-ki/anime-downloader#456]
**Describe the feature here**
Hello, 4anime.to is a great site to stream anime. It offers great quality and fast stream and download.

**Comment by Blatzar** [comment]
Looks good from a glance, will take a look at it later

**Comment by ArjixGamer** [comment]
stop

**Comment by ArjixGamer** [comment]
im already working on it

**Comment by ArjixGamer** [comment]
well , i havent gotten far, since the ajax search just hates me

**Comment by SelectLOL1** [comment]
> im already working on it

**Comment by ArjixGamer** [comment]
so im going to scrape the search results

**Comment by SelectLOL1** [comment]
> well , i havent gotten far, since the ajax search just hates me

Ahahah cool, thank you alot~

**Comment by ArjixGamer** [comment]
the provider is done, pushing the pr in a min
