### ISSUE TITLE
Want to skip through the episodes through commands 

### ISSUE THREAD

**Issue by alansarkar** [vn-ki/anime-downloader#475]
Checked the documentetion but could not find any thing about  skiping episodes while inside the currently watching anime episodes list. mpv can skip through but If i am watching one peace and want to  skip through 100 episodes after words thats not possible.  Is there already a system to skip episodes through cmds  rather than hacking  the json config file ??

**Comment by MichaelDavidJohnson** [comment]
set episodes_done=episodeNumber on the selected anime in watch.
