### ISSUE TITLE
Siteconfig: Set preferred hostname

### ISSUE THREAD

**Issue by IngwiePhoenix** [vn-ki/anime-downloader#479]
9anime has a bunch of alias domains like .ru, .love and such. Sometimes, the AJAX API doesn't work on one domain but will work on another (which has me assuming that their NGINX config must be a nightmare... ^^"). I'd like to be able to set the domain name being used on subsequent requests within siteconfig. For now, I'll hard-edit it in the installation...

**Comment by Blatzar** [comment]
Config for episode_ajax or more stuff like search?
If it's episode_ajax it could be the timeout of 0.3 being to small.

**Comment by IngwiePhoenix** [comment]
Specifically:

* https://github.com/vn-ki/anime-downloader/blob/master/anime_downloader/sites/nineanime.py#L12
* https://github.com/vn-ki/anime-downloader/blob/master/anime_downloader/sites/nineanime.py#L35
* https://github.com/vn-ki/anime-downloader/blob/master/anime_downloader/sites/nineanime.py#L71

I am not a python guy but something like `config[siteconfig].domain || "9anime.to"` should do in all three of these scenarios.

**Comment by IngwiePhoenix** [comment]
> Config for episode_ajax or more stuff like search?
> If it's episode_ajax it could be the timeout of 0.3 being to small.

Nope, got a 503 outright. Retried with cURL. Using `9anime.ru` instead of `.to` works. It's odd... ^^'
