### ISSUE TITLE
Name of anime not being intepreted as a string

### ISSUE THREAD

**Issue by ngomile** [vn-ki/anime-downloader#48]
**description**

When I pass the name of the anime to the dl function, I get an error stating that an extra argument has been passed. It's as if the name of the anime is being split into separate arguments. The command I used is directly copied from the wiki as I was just testing this out now.

```
anime dl 'code geass' --provider kissanime
```

<details>
<summary>LOG</summary>

```
Usage: anime-script.py dl [OPTIONS] ANIME_URL

Error: Got unexpected extra argument (geass')

```
Using Windows 8.1
</details>

**Comment by vn-ki** [comment]
Does this happen with `"` as well? ie `anime dl "code geass"`?

**Comment by ngomile** [comment]
No it does not, thanks though. But strange nonetheless, should probably update the wiki or maybe just a Windows thing.

**Comment by vn-ki** [comment]
Did you fix it somehow? If yes I can update the wiki with the info.
