### ISSUE TITLE
9anime: Firewall triggered

### ISSUE THREAD

**Issue by IngwiePhoenix** [vn-ki/anime-downloader#495]
**Describe the bug**
When making requests to 9anime through the downloader, it will immediately block you, period. I have a few ideas as to why... but this is what I get:

> Our firewall temporarily blocks your IP in 1 hour because of detecting harmful requests..
> Please don't use any unofficial app or browser extension to access to our website to avoid this issue. Thanks!

**To reproduce**
Grab any 9anime show and attempt to download. After the first try, open 9anime.to. You should now see the same text as I do.

**Possible solutions**
- Set a different `User-Agent`
- Set `Refferer` headers according to what a browser would.

**Comment by Blatzar** [comment]
Known issue, I've already (disabled 9anime from init)[https://github.com/vn-ki/anime-downloader/commit/1afef7886d637d61d5af6e5db894fad75c2160d9] to prevent users getting banned. 

Will definitely try to bypass this banning system.

**Comment by Zebraslive** [comment]
@IngwiePhoenix 
The only way around it is using a rotating proxy API. 
This is what I'm using [https://luminati.io](https://luminati.io/?affiliate=ref_5e6a959dc7669177ab5994f7)
it's cheap af with tons of features. I rotate with random country and session hash. using with my own custom downloader.

**Comment by dausruddin** [comment]
Just a warning. Link attached in message above is an affiliate.
Use this if oyu do not wish to use an affiliate link.

https://luminati.io

**Comment by Blatzar** [comment]
Closing in favor of animesuge which seems to have the same sources.

**Comment by IngwiePhoenix** [comment]
> Closing in favor of animesuge which seems to have the same sources.

From their FAQ alone, I would assume it also scrapes 9anime and makes it more accessible that way? I am just verifying that I understood the reason of closure correctly.

**Comment by ArjixGamer** [comment]
From their FAQ I understood that they either scrape other websites for the videos or that it's just a white lie to avoid any legal issues.

**Comment by Blatzar** [comment]
Reason for closure is that 9anime won't be added as animesuge provides the same functionality, but working and with less restrictions.

**Comment by Blatzar** [comment]
9anime and its clones got heavy encryption, reopening issue for if someone finds a fix.

.ru and .to uses different methods, but both have a set length regardless of link, not something ROT13 will solve.
