### ISSUE TITLE
Twist.moe decrypt key

### ISSUE THREAD

**Issue by phanirithvij** [vn-ki/anime-downloader#50]
### Please tell me how you were able to get the key to decrypt api-sources of twist.moe

I spent a huge amount of time inspecting and searching for the key on twist.moe

I am not that familiar with chrome dev tools so (Just an excuse, At the end I was unable to find the key).

I followed some path like

Searched for `Crypto` (hoping they didn't implement their own encryption),
 then found 
```javascript
CryptoJS.AES.decrypt(src, this.sourceKey).toString(CryptoJS.enc.Utf8)
```
 (The decrypting step on twist.moe)

then I searched for `sourceKey`, 
then found 
```javascript
'sourceKey':'e.$options.k'
```

then searched for `$options`, `$options.k`,`$options["k"]` etc...
**but went nowhere.** (I gave up)

I am requesting as a fellow `anime_fan`, `anime_downloader (not a tool)`, `python_user` and a `human` (`male?` :thinking:  etc..) the way which you were able to get the key.

```python
KEY = b"k8B$B@0L8D$tDYHGmRg98sQ7!%GOEGOX27T"
```
:pray: :smile:

**Comment by phanirithvij** [comment]
I'm sorry if you think I suck at **markdown**.

**Comment by phanirithvij** [comment]
I now know that there's a line 

```javascript
            k: "k8B$B@0L8D$tDYHGmRg98sQ7!%GOEGOX27T",
```
somewhere in [_episode.156bab2357aba3633472.js](https://twist.moe/_nuxt/pages/a/_slug/_episode.156bab2357aba3633472.js)

But I found the line just now after seaching the `k8B$B@0L8D$tDYHGmRg98sQ7!%GOEGOX27T`

**Comment by vn-ki** [comment]
Use breakpoints in chrome dev tools. Put a breakpoint in the line of `CryptoJS.AES.decrypt...` and refresh the page. Once execution reaches there look at the variables in watch. Voila. You get the key.

**Comment by phanirithvij** [comment]
Thanks but how can I set a break point at a line in some JavaScript file?

**Comment by vn-ki** [comment]
Just click near the line number in sources tab in chrome dev tools.

**Comment by phanirithvij** [comment]
Thank you very much
I had no idea that it was possible to stop script execution like that
Thanks again
