### ISSUE TITLE
Download Uncen version only for some anime series

### ISSUE THREAD

**Issue by Nompom** [vn-ki/anime-downloader#54]
**Describe the feature here**
I wonder if there's a way to download Uncen version only in a single command instead of download each one of them individually.

**Comment by vn-ki** [comment]
I'm sorry. I don't understand. What's uncen?

**Comment by Nompom** [comment]
Some series has both censored and uncensored version. I want to know if it is possible to download each version independently.

**Comment by vn-ki** [comment]
Can you give an example?

**Comment by Nompom** [comment]
Like this one:

16: High School DxD Hero (Dub)                  DUB | Ep 12-Uncen/12

It has 12 episodes on both version but it say 25 when view the series.

Title: High School DxD Hero (Dub)
episodes_done: 0
Length: 25
Provider: 9anime

**Comment by vn-ki** [comment]
Hmm. Ok. I'll see what I can do about it.

**Comment by FarlsBarkley** [comment]
The episodes are divided so that the odd numbered episodes are the censored ones and the even numbered episodes are uncensored. I don't know if that makes it easier for you.

**Comment by vn-ki** [comment]
@FarlsBarkley Thanks for the info. I was thinking of a more generic solution. Maybe one based on regular expressions. Maybe a new argument `--filter-episodes` which take a regex and filters on basis of it.

**Comment by vn-ki** [comment]
#145
