### ISSUE TITLE
Cross platform GUI with Kivy

### ISSUE THREAD

**Issue by BlackXDragon** [vn-ki/anime-downloader#554]
I think a lot of people would love to have a GUI for this application. To make it cross-platform, I suggest Kivy. Maybe the app could even be packaged into standalone binaries.

If there's some reason it can't or won't be done, do let me know!

**Comment by AbdullahM0hamed** [comment]
Well, it seems to us that Kivy apps tend to look terrible.

Feel free to draft a PR for it though, and if it is better than #526, then you'll have made a solid argument for it's addition.

Although vn-ki has been opposed to it in discussions on the discord server due to the aforementioned reason

**Comment by IguanasInPyjamas** [comment]
We literally have a cross platform nowadays in #526, at least for all PC based systems. Android is pretty much on it's own.

**Comment by BlackXDragon** [comment]
> We literally have a cross platform nowadays in #526, at least for all PC based systems. Android is pretty much on it's own.

@IguanasInPyjamas I didn't notice there was already a GUI in development! I'm pretty new to developing GUI in Python, however, if #526 will possibly be added to the product, I would like to try my hand at helping out.

**Comment by IguanasInPyjamas** [comment]
No problems, there's a couple bugs that need to be ironed out before it merges to main. Free free to work on them!
