### ISSUE TITLE
Resolution Fallback [Feature Request]

### ISSUE THREAD

**Issue by miasmaejuices** [vn-ki/anime-downloader#57]
Hey mate,

Is there any way to implement a standard resolution fallback?

As an example, the flag could be something like `--maxres` which overrides `-q`

The idea would be to automatically try different resolutions in order of highest to lowest.  If a 1080p version is available, it is downloaded and the script moves on to the next episode.

If on the other hand a 1080p version is not available, then it will automatically retry in order of highest resolution to lowest, until it finds a valid download.

Currently, if when using `-q 1080p`, a 1080p version does not exist, it doesn't seem to fallback to 720p, then 480p etc.  Instead, it seems to jump directly to the lowest available resolution.

Thanks!  Great script BTW!  Keep up the great work :)

**Comment by miasmaejuices** [comment]
May have spoken too soon.  Looks like the series had an "Uncen" set of episodes as well.  It might be getting confused between the episodes and their naming etc.  I'll test more in the morning. :)

**Comment by miasmaejuices** [comment]
Confirmed the original issue.  If no 1080p version is found, it automatically falls back to 320p, then progresses upward to 480p, then 720p.

**Comment by vn-ki** [comment]
Yes, this is intentional. I will look into your request. Maybe a new argument `--fallback-quality`?

**Comment by miasmaejuices** [comment]
Interesting.  I kinda understand.  Invariably on 9anime, there are up to 4 different possible resolutions, 1080p, 720p, 480p, and 320p.

I've been testing bash scripting, so enable me to just paste URL's in the script, and letting it do it's thing.

I've setup the defaults in the config for aria2c, and 1080p dl resolutions.  That's solved part of the issue, but when you look at any given show on 9anime, it can have different resolutions per episode, not just per series.  So episode #1, may be 1080p, but episode #5 might only have a 720p. 480p and 320p versions.

If this is the case, instead of downloading the 720p version, it will automatically default to the lowest resolution.

If the `--fallback-quality` can support multiple arguments like this: `--fallback-quality "1080p 720p 480p 320p"`, then it would solve the issue.

Does that make sense?

**Comment by vn-ki** [comment]
Fixed in 3.4.0.

I use `--fallback-qualities "['360p', '480p']"` in zsh, but maybe you don't need the extra quotes in bash. Use `-fq` for short.
