### ISSUE TITLE
Needs Documentation

### ISSUE THREAD

**Issue by ngomile** [vn-ki/anime-downloader#59]
Currently the documentation of anime-downloader is lacking and that's making it difficult to incorporate some changes or just understand what's going on. While I have managed to grasp how this is working for the most part, I think that better comments in the source such as making use of docstrings will be helpful. Not only will this get others like myself up to speed but it will make contributing less painful and understand why some decisions were made. Thank you.

**Comment by vn-ki** [comment]
Please check out the wiki for basic usage.

Also, I agree that the code has to be commented. I was thinking of making use of sphinx and moving the docs to readthedocs.

**Comment by vn-ki** [comment]
Fixed in rewrite
