### ISSUE TITLE
Wiki instructions for Windows Install using the choco package manager

### ISSUE THREAD

**Issue by 1ijack** [vn-ki/anime-downloader#60]
**Describe the feature here**
This is for choco users, or choco users with limited/no understanding of: CLI/python, `pip`, `env`/`path` config, etc.

> Once you choco, you choco for life.

**Proposed Wiki Entry [Installation#WinChoco](https://github.com/vn-ki/anime-downloader/wiki/Installation)**
### Windows via `choco`
- Using the [Chocolatey](https://chocolatey.org/install) Package manager (via Windows Nuget) to 
  - Install these pre-reqs: [git](https://chocolatey.org/packages/git) [python3](https://chocolatey.org/packages/python3) [aria2](https://chocolatey.org/packages/aria2) [mpv](https://chocolatey.org/packages/mpv)
  - Refresh/Update environment changes (choco `refreshenv` command)
  - clone this repository to `[C:]\Users\[USERNAME]\anime-downloader`
  - setup/build anime-downloader from `"%userprofile%\anime-downloader"`
  - run `anime watch` command

- the `choco install` command SHOULD be run with an administrator privledged `cmd.exe` console: 
  - `[WindowsKey] > "cmd.exe" > [Shift]+[Ctrl]+[Enter] > (Click "Yes")`
```
choco install -y git python3 aria2 mpv
```
- the rest of the commands SHOULD be run in an un-privledged/normal `cmd.exe` console: 
  - `[WindowsKey] > "cmd.exe" > [Enter]`
```
refreshenv
git clone https://github.com/vn-ki/anime-downloader "%userprofile%\anime-downloader"
cd /d "%userprofile%\anime-downloader"
setup.py build
setup.py install
anime watch "[insert anime title here]"
```

**Comment by 1ijack** [comment]
this can possibly help #59

**Comment by vn-ki** [comment]
Thanks for the contribution. I have updated the installation wiki.
