### ISSUE TITLE
[Windows] Show titles are cut

### ISSUE THREAD

**Issue by NomNomSu** [vn-ki/anime-downloader#75]
**Describe the bug**

When running in powershell or command line the names of shows are cut and it is not possible to identify shows, resizing window and running command again does not help.

**To reproduce**

```
anime dl 'Hyakuren no Haou to Seiyaku no Valkyria' --provider kissanime
```

<details>
<summary>LOG</summary>
```
DEBUG root: Platform: Windows-10-10.0.17134-SP0
DEBUG root: Python 3.6.2
DEBUG root: The Master of Ragnarok and Blesser of Einherjar (Dub)
DEBUG root: The Master of Ragnarok and Blesser of Einherjar (Sub)
 1: The Master of Ragnarok and Blesser of Ei
 2: The Master of Ragnarok and Blesser of Ei
```
</details>

**Comment by dbourdeveloper** [comment]
Came across this PR and I like the direction of this project! I made a PR #89 to get things rolling on this. Let me know what you think and if we can improve this in another way.
