### ISSUE TITLE
Issue with aria2c

### ISSUE THREAD

**Issue by Hatchetmanx** [vn-ki/anime-downloader#76]
I have tried everything to get anime-downloader with aria2c but keep getting this http://prntscr.com/kqrmka

**Comment by vn-ki** [comment]
```
anime dl "name" --provider provider -xd "{aria2}"
```

From https://github.com/vn-ki/anime-downloader/wiki/dl-command,
> It is recommended to use the external downloader functionality with aria2c because it will be faster than the internal downloader: Use the argument -xd "{aria2}"

**Comment by Hatchetmanx** [comment]
works fine in linux but i get a bunch of python errors in windows when trying to use aria2c.

**Comment by vn-ki** [comment]
You tried using choco on windows? 

https://github.com/vn-ki/anime-downloader/wiki/Installation#windows-via-choco

**Comment by THEGOLDENPRO** [comment]
Has this been fixed. I'm still getting "[WinError 2] The system cannot find the file specified."

**Comment by ArjixWasTaken** [comment]
> Has this been fixed. I'm still getting "[WinError 2] The system cannot find the file specified."

It was not an error in the first place...
Is aria2 on PATH?

To check you can run this command: `where aria2c`
If it says `INFO: Could not find files for the given pattern(s).` then it means that aria2 is not on PATH (and/or not installed at all).

**Comment by THEGOLDENPRO** [comment]
> You tried using choco on windows?
> 
> https://github.com/vn-ki/anime-downloader/wiki/Installation#windows-via-choco

Tried this now I can't do anything.
![image](https://user-images.githubusercontent.com/66202304/128571834-b1eb1974-f1fe-42dc-9e96-87befb205616.png)

**Comment by THEGOLDENPRO** [comment]
> > Has this been fixed. I'm still getting "[WinError 2] The system cannot find the file specified."
> 
> It was not an error in the first place...
> Is aria2 on PATH?
> 
> To check you can run this command: `where aria2c`
> If it says `INFO: Could not find files for the given pattern(s).` then it means that aria2 is not on PATH (and/or not installed at all).

oh let me try this.

**Comment by THEGOLDENPRO** [comment]
> > Has this been fixed. I'm still getting "[WinError 2] The system cannot find the file specified."
> 
> It was not an error in the first place...
> Is aria2 on PATH?
> 
> To check you can run this command: `where aria2c`
> If it says `INFO: Could not find files for the given pattern(s).` then it means that aria2 is not on PATH (and/or not installed at all).

how do I uninstall the anime downloader, I want to start everything fresh.

**Comment by ArjixWasTaken** [comment]
> > > Has this been fixed. I'm still getting "[WinError 2] The system cannot find the file specified."
> > 
> > 
> > It was not an error in the first place...
> > Is aria2 on PATH?
> > To check you can run this command: `where aria2c`
> > If it says `INFO: Could not find files for the given pattern(s).` then it means that aria2 is not on PATH (and/or not installed at all).
> 
> how do I uninstall the anime downloader, I want to start everything fresh.

`pip uninstall anime-downloader`

**Comment by THEGOLDENPRO** [comment]
> > > > Has this been fixed. I'm still getting "[WinError 2] The system cannot find the file specified."
> > > 
> > > 
> > > It was not an error in the first place...
> > > Is aria2 on PATH?
> > > To check you can run this command: `where aria2c`
> > > If it says `INFO: Could not find files for the given pattern(s).` then it means that aria2 is not on PATH (and/or not installed at all).
> > 
> > 
> > how do I uninstall the anime downloader, I want to start everything fresh.
> 
> `pip uninstall anime-downloader`

I feel so dumb, thanks 👍.

**Comment by THEGOLDENPRO** [comment]
@ArjixWasTaken Finally it works, thank you so much for your help.

**Comment by ArjixWasTaken** [comment]
> @ArjixWasTaken Finally it works, thank you so much for your help.

I'm glad to hear that!
