### ISSUE TITLE
Download won't start when using --episodes parameter

### ISSUE THREAD

**Issue by d21m** [vn-ki/anime-downloader#77]
https://prnt.sc/krkgc8

It just stops when it's about to start downloading. Using --url yields the same result in that it just stops. Masterani.me also just stops before it downloads. Is the problem on my end perhaps?

**Comment by vn-ki** [comment]
Can you download without aria2?

**Comment by d21m** [comment]
Strange. I tried it again just now and it works with or without aria2.

**Comment by d21m** [comment]
Tried it on a different anime and it works. Both on kissanime by the way.
