### ISSUE TITLE
I am getting this error when i try download full series or range of episodes from any site.

### ISSUE THREAD

**Issue by su32** [vn-ki/anime-downloader#78]
I am able to download single episode, but getting the same error when trying to download full series.
I either get the error or download doesn't start after selecting choice.
Img link : https://imgur.com/FHTEPJR

**To reproduce**

```
anime dl "dragon ball super" --quality 720p --download-dir "E:\projects"
```

<details>
<summary>LOG</summary>
```



```

**Comment by ExillustX** [comment]
Same issue. However it works if i use `--provider animepahe` .

**Comment by su32** [comment]
Animepahe works, but there are no dub episodes and the anime downloader skips some episodes.

**Comment by vn-ki** [comment]
9anime does not work for now. All other providers should work fine.

**Comment by su32** [comment]
Thanks.
