### ISSUE TITLE
Output URLs to file

### ISSUE THREAD

**Issue by Meisterlala** [vn-ki/anime-downloader#80]
It would be nice if the stream URL would be writen to a file.

Currently when you type `anime dl "overlord" --url > url.txt` the url.txt contains a list of the animes you can select and you have to blindly choose one. Text which is prefixed with "anime: " is still displayed in the console.

You could add another option, e.g. `anime dl "overlord" --url "url.txt"` which writes the stream URLs to that text file. Or you could use the pipe system, e.g. `anime dl "overloard" --url > url.txt` and only output the stream URLs to STDOUT.

**Comment by vn-ki** [comment]
This seems to be a bug. `click.echo` seems to be outputting to stdout instead of stderr.
