### ISSUE TITLE
Can't download in 1080p

### ISSUE THREAD

**Issue by Velkromod** [vn-ki/anime-downloader#87]
Hi! After lot of trial and error I managed to download from kissanime using aria2, but I cant download in 1080p quality, only in 720p, I've checked on the web to confirm that is avariable, yet on the command prompt It says that is not avariable, I might be doing something wrong?
to reproduce:
anime dl "JoJo's Bizarre Adventure: Stardust Crusaders (Sub)" -q 1080p  --provider kissanime -e 8 -xd "{aria2}"

https://i.imgur.com/HXTQVu3.png

**Comment by vn-ki** [comment]
Closed in #88
